In [2]:
import re
import pandas as pd

In [20]:
df_1 = pd.read_csv('โซน หลักหก\df_main_combined11.csv')
df_2 = pd.read_csv('โซน รังสิต\df_main_combined11.csv')
df_3 = pd.read_csv('โซน คลองหนึ่ง\df_main_combined.csv')

In [21]:
df_1.head(2)

,name,lat,long,url,rating,comment,sal1,sal2,id_open_close_main,id_customer_main,id_option_main,id_review_main,zone
0,Cafe Mikka มหาวิทยาลัยรังสิต,13.964464,100.586869,https://www.google.com/maps/place/Cafe+Mikka+%...,3.0,-4,NaN,NaN,oc_300,ci_300,option_300,review_300,rakhok
1,สภาเครป@ม.รังสิต,13.965311,100.589619,https://www.google.com/maps/place/%E0%B8%AA%E0...,5.0,-2,NaN,NaN,oc_301,ci_301,option_301,review_301,rakhok

In [22]:
for df in [df_1, df_2, df_3]:
    df['sal2'] = df['sal2'].str.extract(r'(\d+)').astype(float)

In [23]:
df_1.tail()

,name,lat,long,url,rating,comment,sal1,sal2,id_open_close_main,id_customer_main,id_option_main,id_review_main,zone
61,บ้านคนรักดนตรี by BongBong นมสด,13.966219,100.589250,https://www.google.com/maps/place/%E0%B8%9A%E0...,NaN,NaN,NaN,NaN,oc_403,ci_403,option_403,review_402,rakhok
62,ร้าน บังมูครัวมุสลิม ฮาลาล,13.965209,100.595155,https://www.google.com/maps/place/%E0%B8%A3%E0...,4.9,-17,฿1-100 ต่อคน,8.0,oc_404,ci_404,option_404,review_404,rakhok
63,ร้านอาหาร หัวหิน (เมืองเอก รังสิต),13.972992,100.586772,https://www.google.com/maps/place/%E0%B8%A3%E0...,4.3,-70,NaN,NaN,oc_405,ci_405,option_405,review_405,rakhok
64,The Best Cafe & Restaurant,13.964709,100.727045,https://www.google.com/maps/place/The+Best+Caf...,4.7,-21,NaN,NaN,oc_406,ci_406,option_406,review_406,rakhok
65,หมูกระทะเมืองเอก ต้นตำรับ10ปี โดยคุณกอล์ฟ,13.963706,100.595637,https://www.google.com/maps/place/%E0%B8%AB%E0...,4.6,-52,฿100-200 ต่อคน,19.0,oc_407,ci_407,option_407,review_407,rakhok

In [24]:
df_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 66 entries, 0 to 65
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   name                66 non-null     object
 1   lat                 66 non-null     float64
 2   long                66 non-null     float64
 3   url                 66 non-null     object
 4   rating              55 non-null     float64
 5   comment             55 non-null     object
 6   sal1                18 non-null     object
 7   sal2                18 non-null     float64
 8   id_open_close_main  66 non-null     object
 9   id_customer_main    66 non-null     object
 10  id_option_main      66 non-null     object
 11  id_review_main      66 non-null     object
 12  zone                66 non-null     object
dtypes: float64(4), object(9)
memory usage: 6.8+ KB

In [25]:
for df in [df_1, df_2, df_3]:
    df['comment'] = (
        pd.to_numeric(df['comment'].astype(str).str.replace(',', '', regex=False), errors='coerce')
        .abs()
    )

In [26]:
df_1.head()

,name,lat,long,url,rating,comment,sal1,sal2,id_open_close_main,id_customer_main,id_option_main,id_review_main,zone
0,Cafe Mikka มหาวิทยาลัยรังสิต,13.964464,100.586869,https://www.google.com/maps/place/Cafe+Mikka+%...,3.0,4.0,NaN,NaN,oc_300,ci_300,option_300,review_300,rakhok
1,สภาเครป@ม.รังสิต,13.965311,100.589619,https://www.google.com/maps/place/%E0%B8%AA%E0...,5.0,2.0,NaN,NaN,oc_301,ci_301,option_301,review_301,rakhok
2,Decons cafe,13.965610,100.586142,https://www.google.com/maps/place/Decons+cafe/...,NaN,NaN,NaN,NaN,oc_302,ci_302,option_302,review_301,rakhok
3,Magenta Duck Coffee,13.975879,100.592491,https://www.google.com/maps/place/Magenta+Duck...,3.0,3.0,NaN,NaN,oc_303,ci_303,option_303,review_303,rakhok
4,Kongsi Tea Bar กงสี ทีบาร์ (สาขา ม.รังสิต เมือ...,13.962986,100.587168,https://www.google.com/maps/place/Kongsi+Tea+B...,5.0,2.0,NaN,NaN,oc_304,ci_304,option_304,review_304,rakhok

In [27]:
13.9904187 , 100.5949663 #รังสิต
13.9811737 , 100.5983345 #คลองรังสิต
13.9659073 , 100.5924792 #หลักหก

(13.9659073, 100.5924792)

In [28]:
from haversine import haversine, Unit

point_rangsit = (13.9904187, 100.5949663)  # รังสิต
point_khlong_rangsit = (13.9811737, 100.5983345)  # คลองรังสิต
point_lak_hok = (13.9659073, 100.5924792)  # หลักหก

def add_distance_columns(df):
    df['distance_rangsit'] = df.apply(lambda row: haversine((row['lat'], row['long']), point_rangsit, unit=Unit.KILOMETERS), axis=1)
    df['distance_khlong_rangsit'] = df.apply(lambda row: haversine((row['lat'], row['long']), point_khlong_rangsit, unit=Unit.KILOMETERS), axis=1)
    df['distance_lak_hok'] = df.apply(lambda row: haversine((row['lat'], row['long']), point_lak_hok, unit=Unit.KILOMETERS), axis=1)
    return df

In [29]:
df_1 = add_distance_columns(df_1)
df_2 = add_distance_columns(df_2)
df_3 = add_distance_columns(df_3)

In [30]:
df_1.head()

,name,lat,long,url,rating,comment,sal1,sal2,id_open_close_main,id_customer_main,id_option_main,id_review_main,zone,distance_rangsit,distance_khlong_rangsit,distance_lak_hok
0,Cafe Mikka มหาวิทยาลัยรังสิต,13.964464,100.586869,https://www.google.com/maps/place/Cafe+Mikka+%...,3.0,4.0,NaN,NaN,oc_300,ci_300,option_300,review_300,rakhok,3.015379,2.232222,0.626258
1,สภาเครป@ม.รังสิต,13.965311,100.589619,https://www.google.com/maps/place/%E0%B8%AA%E0...,5.0,2.0,NaN,NaN,oc_301,ci_301,option_301,review_301,rakhok,2.850819,1.998874,0.315674
2,Decons cafe,13.965610,100.586142,https://www.google.com/maps/place/Decons+cafe/...,NaN,NaN,NaN,NaN,oc_302,ci_302,option_302,review_301,rakhok,2.918283,2.173873,0.684591
3,Magenta Duck Coffee,13.975879,100.592491,https://www.google.com/maps/place/Magenta+Duck...,3.0,3.0,NaN,NaN,oc_303,ci_303,option_303,review_303,rakhok,1.638687,0.862676,1.108771
4,Kongsi Tea Bar กงสี ทีบาร์ (สาขา ม.รังสิต เมือ...,13.962986,100.587168,https://www.google.com/maps/place/Kongsi+Tea+B...,5.0,2.0,NaN,NaN,oc_304,ci_304,option_304,review_304,rakhok,3.164347,2.354159,0.658827

In [31]:
df_1.to_csv('df_1_main_clean.csv', index=False,encoding='utf-8-sig')
df_2.to_csv('df_2_main_clean.csv', index=False,encoding='utf-8-sig')
df_3.to_csv('df_3_main_clean.csv', index=False,encoding='utf-8-sig')

# df_ci

In [32]:
df_3_ci = pd.read_csv('โซน คลองหนึ่ง\df_ci_combined.csv')
df_1_ci = pd.read_csv('โซน หลักหก\df_ci_combined11.csv')
df_2_ci = pd.read_csv('โซน รังสิต\df_ci_combined11.csv')

In [33]:
df_1_ci['customer']

0                                                     NaN
1                                                     NaN
2                                                     NaN
3                                                     NaN
4                                                     NaN
                              ...
2187    โดยปกติแล้วเวลา 20:00 จะมีลูกค้าประมาณ 84% เที...
2188    โดยปกติแล้วเวลา 21:00 จะมีลูกค้าประมาณ 74% เที...
2189    โดยปกติแล้วเวลา 22:00 จะมีลูกค้าประมาณ 58% เที...
2190    ปัจจุบันมีลูกค้าประมาณ 0% เทียบกับช่วงเวลาที่ม...
2191    โดยปกติแล้วเวลา 00:00 จะมีลูกค้าประมาณ 27% เที...
Name: customer, Length: 2192, dtype: object

In [34]:
import pandas as pd
import re
from datetime import datetime
import numpy as np

In [35]:
def extract_and_convert(text):
    if pd.isna(text):
        return pd.Series([np.nan, np.nan])
    
    match = re.search(r'เวลา (\d{2}:\d{2}).*?ประมาณ (\d+)%', text)
    if match:
        # แปลงเวลาเป็น datetime.time
        try:
            time_val = datetime.strptime(match.group(1), "%H:%M").time()
        except ValueError:
            time_val = np.nan

        # แปลงเปอร์เซ็นต์เป็น int
        percent_val = int(match.group(2))

        return pd.Series([time_val, percent_val])
    else:
        return pd.Series([np.nan, np.nan])

In [36]:
df_1_ci[['time', 'percent']] = df_1_ci['customer'].apply(extract_and_convert)
df_2_ci[['time', 'percent']] = df_2_ci['customer'].apply(extract_and_convert)
df_3_ci[['time', 'percent']] = df_3_ci['customer'].apply(extract_and_convert)

In [37]:
df_1_ci['time'].unique()

array([nan, datetime.time(6, 0), datetime.time(7, 0), datetime.time(8, 0),
       datetime.time(9, 0), datetime.time(10, 0), datetime.time(11, 0),
       datetime.time(12, 0), datetime.time(13, 0), datetime.time(14, 0),
       datetime.time(15, 0), datetime.time(16, 0), datetime.time(17, 0),
       datetime.time(18, 0), datetime.time(19, 0), datetime.time(20, 0),
       datetime.time(21, 0), datetime.time(22, 0), datetime.time(23, 0),
       datetime.time(0, 0), datetime.time(1, 0), datetime.time(2, 0),
       datetime.time(3, 0), datetime.time(4, 0), datetime.time(5, 0)],
      dtype=object)

In [38]:
df_1_ci['percent'].unique()

array([ nan,   0.,  75.,  62.,  31.,  25.,  12.,  37.,  43.,  50.,  56.,
        18.,  87.,  81.,  68., 100.,   6.,  15.,   7.,  23.,  38.,  53.,
        30.,  61.,  84.,  69.,  76.,  46.,  92.,  32.,  41.,  67.,  70.,
        64.,  77.,  90.,  35.,  48.,  74.,  54.,  51.,  22.,  83.,  45.,
        19.,  29.,  58.,  80.,  93.,  52.,  66.,  71.,  57.,  28.,  33.,
        14.,   9.,  42.,  47.,  85.,  21.,  78.,  88.,  39.,  55.,  63.,
        73.,  40.,  60.,  72.,  82.,  49.,  17.,  34.,  36.,  20.,  96.,
        24.,  79.,  91.,  26.,  10.,  13.,  27.,  44.,  16.,   8.,  86.,
        59.,  65.,  97.,  94.,  95.,  11.,   5.])

In [39]:
df_1_ci

,id_customer_main,customer,customer_day,time,percent
0,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...
2187,ci_407,โดยปกติแล้วเวลา 20:00 จะมีลูกค้าประมาณ 84% เที...,วันเสาร์,20:00:00,84.0
2188,ci_407,โดยปกติแล้วเวลา 21:00 จะมีลูกค้าประมาณ 74% เที...,วันเสาร์,21:00:00,74.0
2189,ci_407,โดยปกติแล้วเวลา 22:00 จะมีลูกค้าประมาณ 58% เที...,วันเสาร์,22:00:00,58.0
2190,ci_407,ปัจจุบันมีลูกค้าประมาณ 0% เทียบกับช่วงเวลาที่ม...,วันเสาร์,NaN,NaN
2191,ci_407,โดยปกติแล้วเวลา 00:00 จะมีลูกค้าประมาณ 27% เที...,วันเสาร์,00:00:00,27.0

In [40]:
df_1_ci.to_csv('df_1_ci_clean.csv', index=False,encoding='utf-8-sig')
df_2_ci.to_csv('df_2_ci_clean.csv', index=False,encoding='utf-8-sig')
df_3_ci.to_csv('df_3_ci_clean.csv', index=False,encoding='utf-8-sig')

# df_op

In [41]:
import pandas as pd

In [42]:
df_3_op = pd.read_csv('โซน คลองหนึ่ง\df_op_combined.csv')
df_1_op = pd.read_csv('โซน หลักหก\df_op_combined11.csv')
df_2_op = pd.read_csv('โซน รังสิต\df_op_combined11.csv')

In [43]:
df_1_op

    id_open_close_main day_open_close  open  close
0               oc_300       วันเสาร์   0.0    0.0
1               oc_300     วันอาทิตย์   0.0    0.0
2               oc_300      วันจันทร์   7.0   16.0
3               oc_300      วันอังคาร   7.0   16.0
4               oc_300         วันพุธ   7.0   16.0
..                 ...            ...   ...    ...
401             oc_407      วันจันทร์  10.0    2.0
402             oc_407      วันอังคาร  10.0    2.0
403             oc_407         วันพุธ  10.0    2.0
404             oc_407    วันพฤหัสบดี  10.0    2.0
405             oc_407       วันศุกร์  10.0    2.0

[406 rows x 4 columns]

In [44]:
df_1_op.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 406 entries, 0 to 405
Data columns (total 4 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id_open_close_main  399 non-null    object
 1   day_open_close      399 non-null    object
 2   open                399 non-null    float64
 3   close               399 non-null    float64
dtypes: float64(2), object(2)
memory usage: 12.8+ KB

In [45]:
df_1_op['open'].unique()

array([ 0. ,  7. ,  nan, 10.3, 10. ,  8. , 17. ,  9. ,  6.3,  7.3, 11. ,
       11.3,  6. ,  8.3,  9.3, 13. , 12. ])

In [46]:
df_1_op['close'].unique()

array([ 0. , 16. ,  nan, 20. , 14. , 19. , 19.3, 18. , 21. , 22. ,  3. ,
       17. ,  5. , 15. , 20.3, 18.3,  2. , 16.3, 23. , 21.3])

In [47]:
from datetime import time

def float_to_time(x):
    if pd.isna(x):
        return None
    hour = int(x)
    minute = int((x - hour) * 100)  # ใช้ *100 ตามที่คุณแจ้ง
    return time(hour, minute)

In [48]:
df_1_op['open_time'] = df_1_op['open'].apply(float_to_time)
df_1_op['open_close'] = df_1_op['close'].apply(float_to_time)
df_2_op['open_time'] = df_2_op['open'].apply(float_to_time)
df_2_op['open_close'] = df_2_op['close'].apply(float_to_time)
df_3_op['open_time'] = df_3_op['open'].apply(float_to_time)
df_3_op['open_close'] = df_3_op['close'].apply(float_to_time)

In [49]:
df_1_op

    id_open_close_main day_open_close  open  close open_time open_close
0               oc_300       วันเสาร์   0.0    0.0  00:00:00   00:00:00
1               oc_300     วันอาทิตย์   0.0    0.0  00:00:00   00:00:00
2               oc_300      วันจันทร์   7.0   16.0  07:00:00   16:00:00
3               oc_300      วันอังคาร   7.0   16.0  07:00:00   16:00:00
4               oc_300         วันพุธ   7.0   16.0  07:00:00   16:00:00
..                 ...            ...   ...    ...       ...        ...
401             oc_407      วันจันทร์  10.0    2.0  10:00:00   02:00:00
402             oc_407      วันอังคาร  10.0    2.0  10:00:00   02:00:00
403             oc_407         วันพุธ  10.0    2.0  10:00:00   02:00:00
404             oc_407    วันพฤหัสบดี  10.0    2.0  10:00:00   02:00:00
405             oc_407       วันศุกร์  10.0    2.0  10:00:00   02:00:00

[406 rows x 6 columns]

In [50]:
df_1_op.to_csv('df_1_open_close_clean.csv', index=False,encoding='utf-8-sig')
df_2_op.to_csv('df_2_open_close_clean.csv', index=False,encoding='utf-8-sig')
df_3_op.to_csv('df_3_open_close_clean.csv', index=False,encoding='utf-8-sig')

# df_option

In [51]:
df_3_option = pd.read_csv('โซน คลองหนึ่ง\df_option_combined.csv')
df_1_option = pd.read_csv('โซน หลักหก\df_option_combined11.csv')
df_2_option = pd.read_csv('โซน รังสิต\df_option_combined11.csv')

In [52]:
print(df_1_option['option'].nunique())
df_1_option['option'].unique()

85

array(['รับสินค้าโดยไม่ต้องลงจากรถ', 'สั่งกลับบ้าน',
       'นั่งรับประทานที่ร้าน', '\ue033', 'บริการจัดส่ง', 'กาแฟ',
       'อาหารสำเร็จ', 'อาหารเช้า', 'อาหารมื้อสาย', 'อาหารกลางวัน',
       'อาหารค่ำ', 'ของหวาน', 'ที่นั่ง', 'ต้องนัดหมายล่วงหน้า', 'รับจอง',
       'ที่จอดรถในพื้นที่', 'ที่จอดรถแบบไม่เสียค่าใช้จ่าย',
       'กาแฟรสชาติเยี่ยม', 'ตัวเลือกชารสเลิศ',
       'เหมาะกับการทำงานด้วยแล็ปท็อป', 'ห้องน้ำ', 'ความเป็นกันเอง',
       'มาเป็นกลุ่ม', 'รับประทานอาหารคนเดียว', 'ทันสมัย', 'อบอุ่น',
       'นักศึกษามหาวิทยาลัย', 'รับเฉพาะเงินสด', 'เมนูสำหรับเด็ก',
       'เหมาะสำหรับเด็ก', 'อาหารจานด่วน', 'อาหารจานเล็ก',
       'ที่จอดรถริมถนนแบบไม่เสียค่าใช้จ่าย', 'ที่นั่งกลางแจ้ง',
       'ขนมหวานรสชาติเยี่ยม', 'จัดส่งโดยไม่สัมผัส', 'อาหารมื้อดึก',
       'ที่จอดรถที่เก้าอี้รถเข็นสามารถใช้ได้', 'ขาจร', 'เงียบ',
       'ทางเข้าสำหรับเก้าอี้รถเข็น', 'ที่นั่งสำหรับเก้าอี้รถเข็น',
       'ระบบอำนวยความสะดวกช่วยเพิ่มการได้ยิน',
       'ห้องน้ำรองรับเก้าอี้รถเข็น', 'การเปิดให้บริการที่หน้าร้าน',
       'บริการจัดเลี้ยง', 'ห้องน้ำไม่แบ่งเพศ', 'Wi-Fi', 'Wi-Fi ฟรี',
       'พื้นที่ที่ยอมรับบุคคลข้ามเพศ', 'เหมาะสำหรับครอบครัว',
       'เหมาะสำหรับ LGBTQ+', 'การชำระเงินผ่าน NFC บนอุปกรณ์เคลื่อนที่',
       'ส่วนลดสำหรับครอบครัว', 'ส่วนลดสําหรับเด็ก',
       'อนุญาตให้สุนัขอยู่ด้านนอก', 'เบียร์', 'แอลกอฮอล์',
       'ระบุว่ามีเจ้าของเป็นผู้หญิง', 'ไวน์', 'เหล้าดีกรีสูง', 'มีบาร์',
       'โรแมนติก', 'บัตรเครดิต', 'มีที่จอดจำนวนมาก',
       'โรงจอดรถแบบไม่เสียค่าใช้จ่าย', 'ไดรฟ์ทรู', 'ค็อกเทล',
       'ช่วงลดราคาเครื่องดื่ม', 'ช่วงลดราคาอาหาร',
       'เก้าอี้ทานข้าวสำหรับเด็ก', 'แนะนำให้จองอาหารมื้อสาย',
       'แนะนำให้จองอาหารกลางวัน', 'แนะนำให้จองอาหารค่ำ', 'โดยปกติต้องรอ',
       'หาที่จอดค่อนข้างยาก', 'รายการไวน์ชั้นดี', 'อาหาร', 'หาที่จอดยาก',
       'อาหารฮาลาล', 'ตัวเลือกเบียร์รสชาติเยี่ยม',
       'ตัวเลือกสำหรับมังสวิรัติ', 'บัตรเดบิต', 'ต้อนรับสุนัข',
       'อนุญาตให้นําสุนัขเข้าไปด้านใน'], dtype=object)

In [53]:
df_1_option['option'] = df_1_option['option'].replace('Wi-Fi ฟรี', 'Wi-Fi')
print(df_1_option['option'].nunique())
df_1_option['option'].unique()

84

array(['รับสินค้าโดยไม่ต้องลงจากรถ', 'สั่งกลับบ้าน',
       'นั่งรับประทานที่ร้าน', '\ue033', 'บริการจัดส่ง', 'กาแฟ',
       'อาหารสำเร็จ', 'อาหารเช้า', 'อาหารมื้อสาย', 'อาหารกลางวัน',
       'อาหารค่ำ', 'ของหวาน', 'ที่นั่ง', 'ต้องนัดหมายล่วงหน้า', 'รับจอง',
       'ที่จอดรถในพื้นที่', 'ที่จอดรถแบบไม่เสียค่าใช้จ่าย',
       'กาแฟรสชาติเยี่ยม', 'ตัวเลือกชารสเลิศ',
       'เหมาะกับการทำงานด้วยแล็ปท็อป', 'ห้องน้ำ', 'ความเป็นกันเอง',
       'มาเป็นกลุ่ม', 'รับประทานอาหารคนเดียว', 'ทันสมัย', 'อบอุ่น',
       'นักศึกษามหาวิทยาลัย', 'รับเฉพาะเงินสด', 'เมนูสำหรับเด็ก',
       'เหมาะสำหรับเด็ก', 'อาหารจานด่วน', 'อาหารจานเล็ก',
       'ที่จอดรถริมถนนแบบไม่เสียค่าใช้จ่าย', 'ที่นั่งกลางแจ้ง',
       'ขนมหวานรสชาติเยี่ยม', 'จัดส่งโดยไม่สัมผัส', 'อาหารมื้อดึก',
       'ที่จอดรถที่เก้าอี้รถเข็นสามารถใช้ได้', 'ขาจร', 'เงียบ',
       'ทางเข้าสำหรับเก้าอี้รถเข็น', 'ที่นั่งสำหรับเก้าอี้รถเข็น',
       'ระบบอำนวยความสะดวกช่วยเพิ่มการได้ยิน',
       'ห้องน้ำรองรับเก้าอี้รถเข็น', 'การเปิดให้บริการที่หน้าร้าน',
       'บริการจัดเลี้ยง', 'ห้องน้ำไม่แบ่งเพศ', 'Wi-Fi',
       'พื้นที่ที่ยอมรับบุคคลข้ามเพศ', 'เหมาะสำหรับครอบครัว',
       'เหมาะสำหรับ LGBTQ+', 'การชำระเงินผ่าน NFC บนอุปกรณ์เคลื่อนที่',
       'ส่วนลดสำหรับครอบครัว', 'ส่วนลดสําหรับเด็ก',
       'อนุญาตให้สุนัขอยู่ด้านนอก', 'เบียร์', 'แอลกอฮอล์',
       'ระบุว่ามีเจ้าของเป็นผู้หญิง', 'ไวน์', 'เหล้าดีกรีสูง', 'มีบาร์',
       'โรแมนติก', 'บัตรเครดิต', 'มีที่จอดจำนวนมาก',
       'โรงจอดรถแบบไม่เสียค่าใช้จ่าย', 'ไดรฟ์ทรู', 'ค็อกเทล',
       'ช่วงลดราคาเครื่องดื่ม', 'ช่วงลดราคาอาหาร',
       'เก้าอี้ทานข้าวสำหรับเด็ก', 'แนะนำให้จองอาหารมื้อสาย',
       'แนะนำให้จองอาหารกลางวัน', 'แนะนำให้จองอาหารค่ำ', 'โดยปกติต้องรอ',
       'หาที่จอดค่อนข้างยาก', 'รายการไวน์ชั้นดี', 'อาหาร', 'หาที่จอดยาก',
       'อาหารฮาลาล', 'ตัวเลือกเบียร์รสชาติเยี่ยม',
       'ตัวเลือกสำหรับมังสวิรัติ', 'บัตรเดบิต', 'ต้อนรับสุนัข',
       'อนุญาตให้นําสุนัขเข้าไปด้านใน'], dtype=object)

In [54]:
print(df_2_option['option'].nunique())
df_2_option['option'].unique()

66

array(['จัดส่งโดยไม่สัมผัส', 'บริการจัดส่ง', 'สั่งกลับบ้าน',
       'นั่งรับประทานที่ร้าน', 'กาแฟรสชาติเยี่ยม', 'ขนมหวานรสชาติเยี่ยม',
       'ตัวเลือกชารสเลิศ', 'อาหารกลางวัน', 'รับประทานอาหารคนเดียว',
       'เหมาะกับการทำงานด้วยแล็ปท็อป', 'กาแฟ', 'อาหารจานด่วน',
       'อาหารจานเล็ก', 'อาหารเช้า', 'อาหารมื้อสาย', 'อาหารค่ำ', 'ของหวาน',
       'ห้องน้ำ', 'Wi-Fi', 'Wi-Fi ฟรี', 'ความเป็นกันเอง', 'เงียบ',
       'ทันสมัย', 'อบอุ่น', 'ขาจร', 'นักศึกษามหาวิทยาลัย',
       'พื้นที่ที่ยอมรับบุคคลข้ามเพศ', 'มาเป็นกลุ่ม',
       'เหมาะสำหรับครอบครัว', 'เหมาะสำหรับ LGBTQ+', 'รับจอง',
       'เมนูสำหรับเด็ก', 'เหมาะสำหรับเด็ก', 'มีที่จอดจำนวนมาก',
       'ที่จอดรถแบบไม่เสียค่าใช้จ่าย',
       'ที่จอดรถริมถนนแบบไม่เสียค่าใช้จ่าย', 'อนุญาตให้สุนัขอยู่ด้านนอก',
       'ที่นั่งกลางแจ้ง', 'ที่นั่ง', 'โรแมนติก',
       'ทางเข้าสำหรับเก้าอี้รถเข็น',
       'ที่จอดรถที่เก้าอี้รถเข็นสามารถใช้ได้', 'บัตรเครดิต', '\ue033',
       'เบียร์', 'แอลกอฮอล์', 'การชำระเงินผ่าน NFC บนอุปกรณ์เคลื่อนที่',
       'รับสินค้าโดยไม่ต้องลงจากรถ', 'การเปิดให้บริการที่หน้าร้าน',
       'การแสดงสด', 'ค็อกเทล', 'เหล้าดีกรีสูง',
       'ที่จอดรถแบบเสียค่าใช้จ่าย', 'ดนตรีสด', 'มารับของที่ร้าน',
       'แวะในช่วงเวลาสั้นๆ', 'ห้องน้ำไม่แบ่งเพศ',
       'ที่นั่งสำหรับเก้าอี้รถเข็น', 'ห้องน้ำรองรับเก้าอี้รถเข็น',
       'ระบบอำนวยความสะดวกช่วยเพิ่มการได้ยิน', 'บัตรเดบิต',
       'หาที่จอดค่อนข้างยาก', 'มีบาร์', 'ไดรฟ์ทรู',
       'ระบุว่ามีเจ้าของเป็นผู้หญิง', 'รับเฉพาะเงินสด'], dtype=object)

In [57]:
df_2_option['option'] = df_2_option['option'].replace('Wi-Fi ฟรี', 'Wi-Fi')
print(df_2_option['option'].nunique())
df_2_option['option'].unique()

64

array(['จัดส่งโดยไม่สัมผัส', 'บริการจัดส่ง', 'สั่งกลับบ้าน',
       'นั่งรับประทานที่ร้าน', 'กาแฟรสชาติเยี่ยม', 'ขนมหวานรสชาติเยี่ยม',
       'ตัวเลือกชารสเลิศ', 'อาหารกลางวัน', 'รับประทานอาหารคนเดียว',
       'เหมาะกับการทำงานด้วยแล็ปท็อป', 'กาแฟ', 'อาหารจานด่วน',
       'อาหารจานเล็ก', 'อาหารเช้า', 'อาหารมื้อสาย', 'อาหารค่ำ', 'ของหวาน',
       'ห้องน้ำ', 'Wi-Fi', 'ความเป็นกันเอง', 'เงียบ', 'ทันสมัย', 'อบอุ่น',
       'ขาจร', 'นักศึกษามหาวิทยาลัย', 'พื้นที่ที่ยอมรับบุคคลข้ามเพศ',
       'มาเป็นกลุ่ม', 'เหมาะสำหรับครอบครัว', 'เหมาะสำหรับ LGBTQ+',
       'รับจอง', 'เมนูสำหรับเด็ก', 'เหมาะสำหรับเด็ก', 'มีที่จอดจำนวนมาก',
       'ที่จอดรถแบบไม่เสียค่าใช้จ่าย',
       'ที่จอดรถริมถนนแบบไม่เสียค่าใช้จ่าย', 'อนุญาตให้สุนัขอยู่ด้านนอก',
       'ที่นั่งกลางแจ้ง', 'ที่นั่ง', 'โรแมนติก',
       'ทางเข้าสำหรับเก้าอี้รถเข็น',
       'ที่จอดรถที่เก้าอี้รถเข็นสามารถใช้ได้', 'บัตรเครดิต', nan,
       'เบียร์', 'แอลกอฮอล์', 'การชำระเงินผ่าน NFC บนอุปกรณ์เคลื่อนที่',
       'รับสินค้าโดยไม่ต้องลงจากรถ', 'การเปิดให้บริการที่หน้าร้าน',
       'การแสดงสด', 'ค็อกเทล', 'เหล้าดีกรีสูง',
       'ที่จอดรถแบบเสียค่าใช้จ่าย', 'ดนตรีสด', 'มารับของที่ร้าน',
       'แวะในช่วงเวลาสั้นๆ', 'ห้องน้ำไม่แบ่งเพศ',
       'ที่นั่งสำหรับเก้าอี้รถเข็น', 'ห้องน้ำรองรับเก้าอี้รถเข็น',
       'ระบบอำนวยความสะดวกช่วยเพิ่มการได้ยิน', 'บัตรเดบิต',
       'หาที่จอดค่อนข้างยาก', 'มีบาร์', 'ไดรฟ์ทรู',
       'ระบุว่ามีเจ้าของเป็นผู้หญิง', 'รับเฉพาะเงินสด'], dtype=object)

In [58]:
df_2_option['option'] = df_2_option['option'].replace('\ue033', np.nan)
print(df_2_option['option'].nunique())
df_2_option['option'].unique()

64

array(['จัดส่งโดยไม่สัมผัส', 'บริการจัดส่ง', 'สั่งกลับบ้าน',
       'นั่งรับประทานที่ร้าน', 'กาแฟรสชาติเยี่ยม', 'ขนมหวานรสชาติเยี่ยม',
       'ตัวเลือกชารสเลิศ', 'อาหารกลางวัน', 'รับประทานอาหารคนเดียว',
       'เหมาะกับการทำงานด้วยแล็ปท็อป', 'กาแฟ', 'อาหารจานด่วน',
       'อาหารจานเล็ก', 'อาหารเช้า', 'อาหารมื้อสาย', 'อาหารค่ำ', 'ของหวาน',
       'ห้องน้ำ', 'Wi-Fi', 'ความเป็นกันเอง', 'เงียบ', 'ทันสมัย', 'อบอุ่น',
       'ขาจร', 'นักศึกษามหาวิทยาลัย', 'พื้นที่ที่ยอมรับบุคคลข้ามเพศ',
       'มาเป็นกลุ่ม', 'เหมาะสำหรับครอบครัว', 'เหมาะสำหรับ LGBTQ+',
       'รับจอง', 'เมนูสำหรับเด็ก', 'เหมาะสำหรับเด็ก', 'มีที่จอดจำนวนมาก',
       'ที่จอดรถแบบไม่เสียค่าใช้จ่าย',
       'ที่จอดรถริมถนนแบบไม่เสียค่าใช้จ่าย', 'อนุญาตให้สุนัขอยู่ด้านนอก',
       'ที่นั่งกลางแจ้ง', 'ที่นั่ง', 'โรแมนติก',
       'ทางเข้าสำหรับเก้าอี้รถเข็น',
       'ที่จอดรถที่เก้าอี้รถเข็นสามารถใช้ได้', 'บัตรเครดิต', nan,
       'เบียร์', 'แอลกอฮอล์', 'การชำระเงินผ่าน NFC บนอุปกรณ์เคลื่อนที่',
       'รับสินค้าโดยไม่ต้องลงจากรถ', 'การเปิดให้บริการที่หน้าร้าน',
       'การแสดงสด', 'ค็อกเทล', 'เหล้าดีกรีสูง',
       'ที่จอดรถแบบเสียค่าใช้จ่าย', 'ดนตรีสด', 'มารับของที่ร้าน',
       'แวะในช่วงเวลาสั้นๆ', 'ห้องน้ำไม่แบ่งเพศ',
       'ที่นั่งสำหรับเก้าอี้รถเข็น', 'ห้องน้ำรองรับเก้าอี้รถเข็น',
       'ระบบอำนวยความสะดวกช่วยเพิ่มการได้ยิน', 'บัตรเดบิต',
       'หาที่จอดค่อนข้างยาก', 'มีบาร์', 'ไดรฟ์ทรู',
       'ระบุว่ามีเจ้าของเป็นผู้หญิง', 'รับเฉพาะเงินสด'], dtype=object)

In [59]:
print(df_3_option['option'].nunique())
df_3_option['option'].unique()

84

array(['สั่งกลับบ้าน', 'นั่งรับประทานที่ร้าน', 'กาแฟรสชาติเยี่ยม',
       'ขนมหวานรสชาติเยี่ยม', 'ตัวเลือกชารสเลิศ', 'รับประทานอาหารคนเดียว',
       'กาแฟ', 'ของหวาน', 'ความเป็นกันเอง', 'ทันสมัย', 'อบอุ่น',
       'นักศึกษามหาวิทยาลัย', 'เมนูสำหรับเด็ก', 'เหมาะสำหรับเด็ก',
       'ที่จอดรถริมถนนแบบไม่เสียค่าใช้จ่าย', 'บริการจัดส่ง',
       'อาหารจานเล็ก', 'ขาจร', 'มาเป็นกลุ่ม', 'มีที่จอดจำนวนมาก',
       'ที่จอดรถแบบไม่เสียค่าใช้จ่าย', 'เหมาะกับการทำงานด้วยแล็ปท็อป',
       'ห้องน้ำ', 'รับสินค้าโดยไม่ต้องลงจากรถ',
       'ที่จอดรถที่เก้าอี้รถเข็นสามารถใช้ได้', 'อาหารกลางวัน', 'เงียบ',
       'รับจอง', 'อาหารค่ำ', 'อาหารมื้อสาย', 'ทางเข้าสำหรับเก้าอี้รถเข็น',
       'ที่นั่งสำหรับเก้าอี้รถเข็น', 'จัดส่งโดยไม่สัมผัส', 'อาหารเช้า',
       'บัตรเครดิต', 'บัตรเดบิต', 'ที่จอดรถแบบเสียค่าใช้จ่าย',
       'อาหารจานด่วน', 'อาหารสำเร็จ', 'Wi-Fi', 'Wi-Fi ฟรี',
       'พื้นที่ที่ยอมรับบุคคลข้ามเพศ', 'รับเฉพาะเงินสด', '\ue033',
       'ที่นั่งกลางแจ้ง', 'ตัวเลือกสำหรับมังสวิรัติ', 'ที่นั่ง',
       'เหมาะสำหรับครอบครัว', 'ไดรฟ์ทรู', 'กีฬา', 'ดนตรีสด',
       'ตัวเลือกเบียร์รสชาติเยี่ยม', 'เบียร์', 'ไวน์', 'เหล้าดีกรีสูง',
       'อาหารมื้อดึก', 'แอลกอฮอล์', 'มีบาร์', 'ต้องจอง',
       'แนะนำให้จองอาหารค่ำ', 'การชำระเงินผ่าน NFC บนอุปกรณ์เคลื่อนที่',
       'หาที่จอดค่อนข้างยาก', 'ระบุว่ามีเจ้าของเป็นผู้หญิง',
       'ระบบอำนวยความสะดวกช่วยเพิ่มการได้ยิน',
       'ห้องน้ำรองรับเก้าอี้รถเข็น', 'มารับของที่ร้าน',
       'การเลือกซื้อในร้านค้า', 'การเปิดให้บริการที่หน้าร้าน',
       'การจัดส่งวันเดียวกัน', 'ห้องน้ำไม่แบ่งเพศ', 'เหมาะสำหรับ LGBTQ+',
       'แวะในช่วงเวลาสั้นๆ', 'อุปกรณ์อิเล็กทรอนิกส์', 'ที่จอดรถในพื้นที่',
       'บริการจัดเลี้ยง', 'ต้อนรับสุนัข', 'อนุญาตให้นําสุนัขเข้าไปด้านใน',
       'อนุญาตให้สุนัขอยู่ด้านนอก', 'บุฟเฟ่ต์', 'แนะนำให้จองอาหารมื้อสาย',
       'แนะนำให้จองอาหารกลางวัน', 'โดยปกติต้องรอ',
       'เก้าอี้ทานข้าวสำหรับเด็ก', 'ช่วงลดราคาอาหาร'], dtype=object)

In [60]:
df_3_option['option'] = df_3_option['option'].replace('Wi-Fi ฟรี', 'Wi-Fi')
print(df_3_option['option'].nunique())
df_3_option['option'].unique()

83

array(['สั่งกลับบ้าน', 'นั่งรับประทานที่ร้าน', 'กาแฟรสชาติเยี่ยม',
       'ขนมหวานรสชาติเยี่ยม', 'ตัวเลือกชารสเลิศ', 'รับประทานอาหารคนเดียว',
       'กาแฟ', 'ของหวาน', 'ความเป็นกันเอง', 'ทันสมัย', 'อบอุ่น',
       'นักศึกษามหาวิทยาลัย', 'เมนูสำหรับเด็ก', 'เหมาะสำหรับเด็ก',
       'ที่จอดรถริมถนนแบบไม่เสียค่าใช้จ่าย', 'บริการจัดส่ง',
       'อาหารจานเล็ก', 'ขาจร', 'มาเป็นกลุ่ม', 'มีที่จอดจำนวนมาก',
       'ที่จอดรถแบบไม่เสียค่าใช้จ่าย', 'เหมาะกับการทำงานด้วยแล็ปท็อป',
       'ห้องน้ำ', 'รับสินค้าโดยไม่ต้องลงจากรถ',
       'ที่จอดรถที่เก้าอี้รถเข็นสามารถใช้ได้', 'อาหารกลางวัน', 'เงียบ',
       'รับจอง', 'อาหารค่ำ', 'อาหารมื้อสาย', 'ทางเข้าสำหรับเก้าอี้รถเข็น',
       'ที่นั่งสำหรับเก้าอี้รถเข็น', 'จัดส่งโดยไม่สัมผัส', 'อาหารเช้า',
       'บัตรเครดิต', 'บัตรเดบิต', 'ที่จอดรถแบบเสียค่าใช้จ่าย',
       'อาหารจานด่วน', 'อาหารสำเร็จ', 'Wi-Fi',
       'พื้นที่ที่ยอมรับบุคคลข้ามเพศ', 'รับเฉพาะเงินสด', '\ue033',
       'ที่นั่งกลางแจ้ง', 'ตัวเลือกสำหรับมังสวิรัติ', 'ที่นั่ง',
       'เหมาะสำหรับครอบครัว', 'ไดรฟ์ทรู', 'กีฬา', 'ดนตรีสด',
       'ตัวเลือกเบียร์รสชาติเยี่ยม', 'เบียร์', 'ไวน์', 'เหล้าดีกรีสูง',
       'อาหารมื้อดึก', 'แอลกอฮอล์', 'มีบาร์', 'ต้องจอง',
       'แนะนำให้จองอาหารค่ำ', 'การชำระเงินผ่าน NFC บนอุปกรณ์เคลื่อนที่',
       'หาที่จอดค่อนข้างยาก', 'ระบุว่ามีเจ้าของเป็นผู้หญิง',
       'ระบบอำนวยความสะดวกช่วยเพิ่มการได้ยิน',
       'ห้องน้ำรองรับเก้าอี้รถเข็น', 'มารับของที่ร้าน',
       'การเลือกซื้อในร้านค้า', 'การเปิดให้บริการที่หน้าร้าน',
       'การจัดส่งวันเดียวกัน', 'ห้องน้ำไม่แบ่งเพศ', 'เหมาะสำหรับ LGBTQ+',
       'แวะในช่วงเวลาสั้นๆ', 'อุปกรณ์อิเล็กทรอนิกส์', 'ที่จอดรถในพื้นที่',
       'บริการจัดเลี้ยง', 'ต้อนรับสุนัข', 'อนุญาตให้นําสุนัขเข้าไปด้านใน',
       'อนุญาตให้สุนัขอยู่ด้านนอก', 'บุฟเฟ่ต์', 'แนะนำให้จองอาหารมื้อสาย',
       'แนะนำให้จองอาหารกลางวัน', 'โดยปกติต้องรอ',
       'เก้าอี้ทานข้าวสำหรับเด็ก', 'ช่วงลดราคาอาหาร'], dtype=object)

In [61]:
df_3_option['option'] = df_3_option['option'].replace('\ue033', np.nan)
print(df_3_option['option'].nunique())
df_3_option['option'].unique()

82

array(['สั่งกลับบ้าน', 'นั่งรับประทานที่ร้าน', 'กาแฟรสชาติเยี่ยม',
       'ขนมหวานรสชาติเยี่ยม', 'ตัวเลือกชารสเลิศ', 'รับประทานอาหารคนเดียว',
       'กาแฟ', 'ของหวาน', 'ความเป็นกันเอง', 'ทันสมัย', 'อบอุ่น',
       'นักศึกษามหาวิทยาลัย', 'เมนูสำหรับเด็ก', 'เหมาะสำหรับเด็ก',
       'ที่จอดรถริมถนนแบบไม่เสียค่าใช้จ่าย', 'บริการจัดส่ง',
       'อาหารจานเล็ก', 'ขาจร', 'มาเป็นกลุ่ม', 'มีที่จอดจำนวนมาก',
       'ที่จอดรถแบบไม่เสียค่าใช้จ่าย', 'เหมาะกับการทำงานด้วยแล็ปท็อป',
       'ห้องน้ำ', 'รับสินค้าโดยไม่ต้องลงจากรถ',
       'ที่จอดรถที่เก้าอี้รถเข็นสามารถใช้ได้', 'อาหารกลางวัน', 'เงียบ',
       'รับจอง', 'อาหารค่ำ', 'อาหารมื้อสาย', 'ทางเข้าสำหรับเก้าอี้รถเข็น',
       'ที่นั่งสำหรับเก้าอี้รถเข็น', 'จัดส่งโดยไม่สัมผัส', 'อาหารเช้า',
       'บัตรเครดิต', 'บัตรเดบิต', 'ที่จอดรถแบบเสียค่าใช้จ่าย',
       'อาหารจานด่วน', 'อาหารสำเร็จ', 'Wi-Fi',
       'พื้นที่ที่ยอมรับบุคคลข้ามเพศ', 'รับเฉพาะเงินสด', nan,
       'ที่นั่งกลางแจ้ง', 'ตัวเลือกสำหรับมังสวิรัติ', 'ที่นั่ง',
       'เหมาะสำหรับครอบครัว', 'ไดรฟ์ทรู', 'กีฬา', 'ดนตรีสด',
       'ตัวเลือกเบียร์รสชาติเยี่ยม', 'เบียร์', 'ไวน์', 'เหล้าดีกรีสูง',
       'อาหารมื้อดึก', 'แอลกอฮอล์', 'มีบาร์', 'ต้องจอง',
       'แนะนำให้จองอาหารค่ำ', 'การชำระเงินผ่าน NFC บนอุปกรณ์เคลื่อนที่',
       'หาที่จอดค่อนข้างยาก', 'ระบุว่ามีเจ้าของเป็นผู้หญิง',
       'ระบบอำนวยความสะดวกช่วยเพิ่มการได้ยิน',
       'ห้องน้ำรองรับเก้าอี้รถเข็น', 'มารับของที่ร้าน',
       'การเลือกซื้อในร้านค้า', 'การเปิดให้บริการที่หน้าร้าน',
       'การจัดส่งวันเดียวกัน', 'ห้องน้ำไม่แบ่งเพศ', 'เหมาะสำหรับ LGBTQ+',
       'แวะในช่วงเวลาสั้นๆ', 'อุปกรณ์อิเล็กทรอนิกส์', 'ที่จอดรถในพื้นที่',
       'บริการจัดเลี้ยง', 'ต้อนรับสุนัข', 'อนุญาตให้นําสุนัขเข้าไปด้านใน',
       'อนุญาตให้สุนัขอยู่ด้านนอก', 'บุฟเฟ่ต์', 'แนะนำให้จองอาหารมื้อสาย',
       'แนะนำให้จองอาหารกลางวัน', 'โดยปกติต้องรอ',
       'เก้าอี้ทานข้าวสำหรับเด็ก', 'ช่วงลดราคาอาหาร'], dtype=object)

In [62]:
df_1_option.to_csv('df_1_option_clean.csv', index=False,encoding='utf-8-sig')
df_2_option.to_csv('df_2_option_clean.csv', index=False,encoding='utf-8-sig')
df_3_option.to_csv('df_3_option_clean.csv', index=False,encoding='utf-8-sig')

# df_review

ทำอีกไฟล์

In [63]:
df_3_review = pd.read_csv('โซน คลองหนึ่ง\df_review_combined.csv')
df_1_review = pd.read_csv('โซน หลักหก\df_review_combined11.csv')
df_2_review = pd.read_csv('โซน รังสิต\df_review_combined11.csv')

In [64]:
import pandas as pd

In [3]:
pd.read_csv('https://raw.githubusercontent.com/Eieiz007/Datasets/refs/heads/main/df_main_clean.csv?token=GHSAT0AAAAAADA4QXIATC5E6CGFDA5KCRS42APGLNA')

,name,lat,long,url,rating,comment,sal1,sal2,id_open_close_main,id_customer_main,id_option_main,id_review_main,zone,distance_rangsit,distance_khlong_rangsit,distance_lak_hok
0,Theme Cafe & Bistro,13.961911,100.605467,https://www.google.com/maps/place/Theme+Cafe+%...,4.4,69.0,NaN,NaN,oc_1,ci_1,option_1,review_1,rakhok,3.366392,2.276054,1.470299
1,Shelter specialty coffee,13.962536,100.585268,https://www.google.com/maps/place/Shelter+spec...,4.8,147.0,฿100-200 ต่อคน,78.0,oc_2,ci_2,option_2,review_2,rakhok,3.272303,2.506605,0.863776
2,ภูมิใจเสนอ Poomjai Saner café & coworking space,13.965177,100.599799,https://www.google.com/maps/place/%E0%B8%A0%E0...,4.7,98.0,฿100-200 ต่อคน,30.0,oc_3,ci_3,option_3,review_3,rakhok,2.854773,1.785755,0.793977
3,ใบแมว คาเฟ่แมว รังสิต,13.963064,100.587933,https://www.google.com/maps/place/%E0%B9%83%E0...,4.4,48.0,฿100-200 ต่อคน,21.0,oc_4,ci_4,option_4,review_4,rakhok,3.134911,2.305347,0.583634
4,Mori Cat Cafe’,13.965271,100.589427,https://www.google.com/maps/place/Mori+Cat+Caf...,4.9,124.0,฿100-200 ต่อคน,40.0,oc_5,ci_5,option_5,review_5,rakhok,2.859427,2.012612,0.336883
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
165,Owlvee Soft | Future Park Rangsit,13.989605,100.616846,https://www.google.com/maps/place/Owlvee+Soft+...,4.0,12.0,฿1-100 ต่อคน,4.0,oc_166,ci_166,option_166,review_166,rungsit,2.362460,2.206453,3.722446
166,พิซซ่าเตาดินสองไร่สโลว์ไลฟ์ฟาร์ม รังสิต คลองสาม,14.021239,100.675426,https://www.google.com/maps/place/%E0%B8%9E%E0...,4.5,87.0,฿200-300 ต่อคน,13.0,oc_167,ci_167,option_167,review_167,rungsit,9.332748,9.435511,10.860451
167,ดอยมูเซอคอฟฟี่@ตลาดรังสิต,13.986671,100.613261,https://www.google.com/maps/place/%E0%B8%94%E0...,5.0,1.0,NaN,NaN,oc_168,ci_168,option_168,review_168,rungsit,2.017449,1.722628,3.218512
168,NJ coffee มอรังสิต,13.964200,100.592048,https://www.google.com/maps/place/NJ+coffee+%E...,3.0,2.0,NaN,NaN,oc_169,ci_169,option_169,review_169,rungsit,2.932347,2.005592,0.195462
169,Coffee World - Future Rangsit Triangle 1st Fl,13.987520,100.618070,https://www.google.com/maps/place/Coffee+World...,4.4,19.0,฿100-200 ต่อคน,9.0,oc_170,ci_170,option_170,review_170,rungsit,2.513549,2.243294,3.660618