In [1]:
import re
import pandas as pd

In [2]:
df_1 = pd.read_csv('โซน หลักหก\df_main_combined.csv')
df_2 = pd.read_csv('โซน รังสิต\df_main_combined3.csv')
df_3 = pd.read_csv('โซน คลองหนึ่ง\df_main_combined2.csv')

In [3]:
df_1.head(2)

,name,lat,long,url,rating,comment,sal1,sal2,id_open_close_main,id_customer_main,id_option_main,id_review_main,zone
0,Theme Cafe & Bistro,13.961911,100.605467,https://www.google.com/maps/place/Theme+Cafe+%...,4.4,-69.0,NaN,NaN,oc_1,ci_1,option_1,review_1,rakhok
1,Shelter specialty coffee,13.962536,100.585268,https://www.google.com/maps/place/Shelter+spec...,4.8,-147.0,฿100-200 ต่อคน,รายงานโดยผู้ใช้ 78 ราย,oc_2,ci_2,option_2,review_2,rakhok

In [4]:
for df in [df_1, df_2, df_3]:
    df['sal2'] = df['sal2'].str.extract(r'(\d+)').astype(float)

In [5]:
df_1.head()

,name,lat,long,url,rating,comment,sal1,sal2,id_open_close_main,id_customer_main,id_option_main,id_review_main,zone
0,Theme Cafe & Bistro,13.961911,100.605467,https://www.google.com/maps/place/Theme+Cafe+%...,4.4,-69.0,NaN,NaN,oc_1,ci_1,option_1,review_1,rakhok
1,Shelter specialty coffee,13.962536,100.585268,https://www.google.com/maps/place/Shelter+spec...,4.8,-147.0,฿100-200 ต่อคน,78.0,oc_2,ci_2,option_2,review_2,rakhok
2,ภูมิใจเสนอ Poomjai Saner café & coworking space,13.965177,100.599799,https://www.google.com/maps/place/%E0%B8%A0%E0...,4.7,-98.0,฿100-200 ต่อคน,30.0,oc_3,ci_3,option_3,review_3,rakhok
3,ใบแมว คาเฟ่แมว รังสิต,13.963064,100.587933,https://www.google.com/maps/place/%E0%B9%83%E0...,4.4,-48.0,฿100-200 ต่อคน,21.0,oc_4,ci_4,option_4,review_4,rakhok
4,Mori Cat Cafe’,13.965271,100.589427,https://www.google.com/maps/place/Mori+Cat+Caf...,4.9,-124.0,฿100-200 ต่อคน,40.0,oc_5,ci_5,option_5,review_5,rakhok

In [6]:
df_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   name                52 non-null     object
 1   lat                 52 non-null     float64
 2   long                52 non-null     float64
 3   url                 52 non-null     object
 4   rating              44 non-null     float64
 5   comment             44 non-null     float64
 6   sal1                20 non-null     object
 7   sal2                20 non-null     float64
 8   id_open_close_main  46 non-null     object
 9   id_customer_main    52 non-null     object
 10  id_option_main      52 non-null     object
 11  id_review_main      52 non-null     object
 12  zone                52 non-null     object
dtypes: float64(5), object(8)
memory usage: 5.4+ KB

In [7]:
for df in [df_1, df_2, df_3]:
    df['comment'] = (
        pd.to_numeric(df['comment'].astype(str).str.replace(',', '', regex=False), errors='coerce')
        .abs()
    )

In [9]:
df_1.head()

,name,lat,long,url,rating,comment,sal1,sal2,id_open_close_main,id_customer_main,id_option_main,id_review_main,zone
0,Theme Cafe & Bistro,13.961911,100.605467,https://www.google.com/maps/place/Theme+Cafe+%...,4.4,69.0,NaN,NaN,oc_1,ci_1,option_1,review_1,rakhok
1,Shelter specialty coffee,13.962536,100.585268,https://www.google.com/maps/place/Shelter+spec...,4.8,147.0,฿100-200 ต่อคน,78.0,oc_2,ci_2,option_2,review_2,rakhok
2,ภูมิใจเสนอ Poomjai Saner café & coworking space,13.965177,100.599799,https://www.google.com/maps/place/%E0%B8%A0%E0...,4.7,98.0,฿100-200 ต่อคน,30.0,oc_3,ci_3,option_3,review_3,rakhok
3,ใบแมว คาเฟ่แมว รังสิต,13.963064,100.587933,https://www.google.com/maps/place/%E0%B9%83%E0...,4.4,48.0,฿100-200 ต่อคน,21.0,oc_4,ci_4,option_4,review_4,rakhok
4,Mori Cat Cafe’,13.965271,100.589427,https://www.google.com/maps/place/Mori+Cat+Caf...,4.9,124.0,฿100-200 ต่อคน,40.0,oc_5,ci_5,option_5,review_5,rakhok

In [ ]:
13.9904187 , 100.5949663 #รังสิต
13.9811737 , 100.5983345 #คลองรังสิต
13.9659073 , 100.5924792 #หลักหก

In [ ]:
from haversine import haversine, Unit

point_rangsit = (13.9904187, 100.5949663)  # รังสิต
point_khlong_rangsit = (13.9811737, 100.5983345)  # คลองรังสิต
point_lak_hok = (13.9659073, 100.5924792)  # หลักหก

def add_distance_columns(df):
    df['distance_rangsit'] = df.apply(lambda row: haversine((row['lat'], row['long']), point_rangsit, unit=Unit.KILOMETERS), axis=1)
    df['distance_khlong_rangsit'] = df.apply(lambda row: haversine((row['lat'], row['long']), point_khlong_rangsit, unit=Unit.KILOMETERS), axis=1)
    df['distance_lak_hok'] = df.apply(lambda row: haversine((row['lat'], row['long']), point_lak_hok, unit=Unit.KILOMETERS), axis=1)
    return df

In [11]:
df_1 = add_distance_columns(df_1)
df_2 = add_distance_columns(df_2)
df_3 = add_distance_columns(df_3)

In [12]:
df_1.head()

,name,lat,long,url,rating,comment,sal1,sal2,id_open_close_main,id_customer_main,id_option_main,id_review_main,zone,distance_rangsit,distance_khlong_rangsit,distance_lak_hok
0,Theme Cafe & Bistro,13.961911,100.605467,https://www.google.com/maps/place/Theme+Cafe+%...,4.4,69.0,NaN,NaN,oc_1,ci_1,option_1,review_1,rakhok,3.366392,2.276054,1.470299
1,Shelter specialty coffee,13.962536,100.585268,https://www.google.com/maps/place/Shelter+spec...,4.8,147.0,฿100-200 ต่อคน,78.0,oc_2,ci_2,option_2,review_2,rakhok,3.272303,2.506605,0.863776
2,ภูมิใจเสนอ Poomjai Saner café & coworking space,13.965177,100.599799,https://www.google.com/maps/place/%E0%B8%A0%E0...,4.7,98.0,฿100-200 ต่อคน,30.0,oc_3,ci_3,option_3,review_3,rakhok,2.854773,1.785755,0.793977
3,ใบแมว คาเฟ่แมว รังสิต,13.963064,100.587933,https://www.google.com/maps/place/%E0%B9%83%E0...,4.4,48.0,฿100-200 ต่อคน,21.0,oc_4,ci_4,option_4,review_4,rakhok,3.134911,2.305347,0.583634
4,Mori Cat Cafe’,13.965271,100.589427,https://www.google.com/maps/place/Mori+Cat+Caf...,4.9,124.0,฿100-200 ต่อคน,40.0,oc_5,ci_5,option_5,review_5,rakhok,2.859427,2.012612,0.336883

In [52]:
df_1.to_csv('df_1_main_clean.csv', index=False,encoding='utf-8-sig')
df_2.to_csv('df_2_main_clean.csv', index=False,encoding='utf-8-sig')
df_3.to_csv('df_3_main_clean.csv', index=False,encoding='utf-8-sig')

# df_ci

In [43]:
df_1_ci = pd.read_csv('โซน หลักหก\df_ci_combined.csv')
df_2_ci = pd.read_csv('โซน รังสิต\df_ci_combined3.csv')
df_3_ci = pd.read_csv('โซน คลองหนึ่ง\df_ci_combined2.csv')

In [44]:
df_1_ci['customer']

0       โดยปกติแล้วเวลา 06:00 จะมีลูกค้าประมาณ 0% เทีย...
1       โดยปกติแล้วเวลา 07:00 จะมีลูกค้าประมาณ 0% เทีย...
2       โดยปกติแล้วเวลา 08:00 จะมีลูกค้าประมาณ 0% เทีย...
3       โดยปกติแล้วเวลา 09:00 จะมีลูกค้าประมาณ 0% เทีย...
4       โดยปกติแล้วเวลา 10:00 จะมีลูกค้าประมาณ 27% เที...
                              ...
1902                                                  NaN
1903                                                  NaN
1904                                                  NaN
1905                                                  NaN
1906                                                  NaN
Name: customer, Length: 1907, dtype: object

In [ ]:
import pandas as pd
import re
from datetime import datetime
import numpy as np

In [ ]:
def extract_and_convert(text):
    if pd.isna(text):
        return pd.Series([np.nan, np.nan])
    
    match = re.search(r'เวลา (\d{2}:\d{2}).*?ประมาณ (\d+)%', text)
    if match:
        # แปลงเวลาเป็น datetime.time
        try:
            time_val = datetime.strptime(match.group(1), "%H:%M").time()
        except ValueError:
            time_val = np.nan

        # แปลงเปอร์เซ็นต์เป็น int
        percent_val = int(match.group(2))

        return pd.Series([time_val, percent_val])
    else:
        return pd.Series([np.nan, np.nan])

In [48]:
df_1_ci[['time', 'percent']] = df_1_ci['customer'].apply(extract_and_convert)
df_2_ci[['time', 'percent']] = df_2_ci['customer'].apply(extract_and_convert)
df_3_ci[['time', 'percent']] = df_3_ci['customer'].apply(extract_and_convert)

In [49]:
df_1_ci['time'].unique()

array([datetime.time(6, 0), datetime.time(7, 0), datetime.time(8, 0),
       datetime.time(9, 0), datetime.time(10, 0), datetime.time(11, 0),
       datetime.time(12, 0), datetime.time(13, 0), datetime.time(14, 0),
       datetime.time(15, 0), datetime.time(16, 0), datetime.time(17, 0),
       datetime.time(18, 0), datetime.time(19, 0), datetime.time(20, 0),
       datetime.time(21, 0), datetime.time(22, 0), datetime.time(23, 0),
       nan, datetime.time(5, 0), datetime.time(0, 0), datetime.time(1, 0),
       datetime.time(2, 0), datetime.time(3, 0), datetime.time(4, 0)],
      dtype=object)

In [50]:
df_1_ci['percent'].unique()

array([  0.,  27.,  33.,  38.,  16.,  22.,  44.,  66.,  50.,  61.,  77.,
        nan,  11.,   5.,  55.,  88., 100.,  72.,  34.,  46.,  69.,  76.,
        57.,  23.,  30.,  26.,  53.,  65.,  42.,  15.,   3.,  19.,   7.,
        73.,  80.,  48.,  51.,  68.,  75.,  31.,  60.,  82.,  97.,  93.,
        91.,  35.,  37.,  62.,  64.,  71.,  86.,  89.,  83.,  81.,  59.,
        45.,  54.,  43.,  67.,  29.,  40.,  24.,  10.,  56.,  94.,  14.,
        20.,  36.,  70.,  92.,  85.,  58.,  63.,  90.,  98.,  84.,  25.,
        87.,  79.,  28.,  32.,  18.,  74.,  47.,  41.,  39.,  12.,   6.,
        13.,  95.,  52.,  78.,  21.])

In [51]:
df_1_ci

,id_customer_main,customer,customer_day,time,percent
0,ci_1,โดยปกติแล้วเวลา 06:00 จะมีลูกค้าประมาณ 0% เทีย...,วันอาทิตย์,06:00:00,0.0
1,ci_1,โดยปกติแล้วเวลา 07:00 จะมีลูกค้าประมาณ 0% เทีย...,วันอาทิตย์,07:00:00,0.0
2,ci_1,โดยปกติแล้วเวลา 08:00 จะมีลูกค้าประมาณ 0% เทีย...,วันอาทิตย์,08:00:00,0.0
3,ci_1,โดยปกติแล้วเวลา 09:00 จะมีลูกค้าประมาณ 0% เทีย...,วันอาทิตย์,09:00:00,0.0
4,ci_1,โดยปกติแล้วเวลา 10:00 จะมีลูกค้าประมาณ 27% เที...,วันอาทิตย์,10:00:00,27.0
...,...,...,...,...,...
1902,NaN,NaN,NaN,NaN,NaN
1903,NaN,NaN,NaN,NaN,NaN
1904,NaN,NaN,NaN,NaN,NaN
1905,NaN,NaN,NaN,NaN,NaN
1906,NaN,NaN,NaN,NaN,NaN

In [53]:
df_1_ci.to_csv('df_1_ci_clean.csv', index=False,encoding='utf-8-sig')
df_2_ci.to_csv('df_2_ci_clean.csv', index=False,encoding='utf-8-sig')
df_3_ci.to_csv('df_3_ci_clean.csv', index=False,encoding='utf-8-sig')

# df_op

In [2]:
import pandas as pd

In [3]:
df_1_op = pd.read_csv('โซน หลักหก\df_op_combined.csv')
df_2_op = pd.read_csv('โซน รังสิต\df_op_combined3.csv')
df_3_op = pd.read_csv('โซน คลองหนึ่ง\df_op_combined2.csv')

In [4]:
df_1_op

    id_open_close_main day_open_close  open  close
0                 oc_1         วันพุธ  10.0    0.0
1                 oc_1    วันพฤหัสบดี  10.0    0.0
2                 oc_1       วันศุกร์  10.0    0.0
3                 oc_1       วันเสาร์  10.0    0.0
4                 oc_1     วันอาทิตย์  10.0    0.0
..                 ...            ...   ...    ...
305              oc_52     วันอาทิตย์   7.0   18.0
306              oc_52      วันจันทร์   7.0   18.0
307              oc_52      วันอังคาร   7.0   18.0
308              oc_52         วันพุธ   7.0   18.0
309              oc_52    วันพฤหัสบดี   7.0   18.0

[310 rows x 4 columns]

In [4]:
df_1_op.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 310 entries, 0 to 309
Data columns (total 4 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id_open_close_main  301 non-null    object
 1   day_open_close      301 non-null    object
 2   open                301 non-null    float64
 3   close               301 non-null    float64
dtypes: float64(2), object(2)
memory usage: 9.8+ KB

In [7]:
df_1_op['open'].unique()

array([10. ,  8. , 11. , 12. ,  nan,  7. ,  6. ,  9. ,  0. ,  7.3,  2. ,
        6.3, 15. ,  9.3,  8.3, 10.3])

In [8]:
df_1_op['close'].unique()

array([ 0.  , 21.3 , 20.  ,   nan, 18.  , 21.  , 23.  ,  1.  , 17.3 ,
        8.09, 22.  , 19.  , 17.  , 18.3 , 15.  ])

In [5]:
from datetime import time

def float_to_time(x):
    if pd.isna(x):
        return None
    hour = int(x)
    minute = int((x - hour) * 100)  # ใช้ *100 ตามที่คุณแจ้ง
    return time(hour, minute)

In [6]:
df_1_op['open_time'] = df_1_op['open'].apply(float_to_time)
df_1_op['open_close'] = df_1_op['close'].apply(float_to_time)
df_2_op['open_time'] = df_2_op['open'].apply(float_to_time)
df_2_op['open_close'] = df_2_op['close'].apply(float_to_time)
df_3_op['open_time'] = df_3_op['open'].apply(float_to_time)
df_3_op['open_close'] = df_3_op['close'].apply(float_to_time)

In [14]:
df_1_op

    id_open_close_main day_open_close  open  close open_time open_close
0                 oc_1         วันพุธ  10.0    0.0  10:00:00   00:00:00
1                 oc_1    วันพฤหัสบดี  10.0    0.0  10:00:00   00:00:00
2                 oc_1       วันศุกร์  10.0    0.0  10:00:00   00:00:00
3                 oc_1       วันเสาร์  10.0    0.0  10:00:00   00:00:00
4                 oc_1     วันอาทิตย์  10.0    0.0  10:00:00   00:00:00
..                 ...            ...   ...    ...       ...        ...
305              oc_52     วันอาทิตย์   7.0   18.0  07:00:00   18:00:00
306              oc_52      วันจันทร์   7.0   18.0  07:00:00   18:00:00
307              oc_52      วันอังคาร   7.0   18.0  07:00:00   18:00:00
308              oc_52         วันพุธ   7.0   18.0  07:00:00   18:00:00
309              oc_52    วันพฤหัสบดี   7.0   18.0  07:00:00   18:00:00

[310 rows x 6 columns]

In [7]:
df_1_op.to_csv('df_1_open_close_clean.csv', index=False,encoding='utf-8-sig')
df_2_op.to_csv('df_2_open_close_clean.csv', index=False,encoding='utf-8-sig')
df_3_op.to_csv('df_3_open_close_clean.csv', index=False,encoding='utf-8-sig')

# df_option

In [58]:
df_1_option = pd.read_csv('โซน หลักหก\df_option_combined.csv')
df_2_option = pd.read_csv('โซน รังสิต\df_option_combined3.csv')
df_3_option = pd.read_csv('โซน คลองหนึ่ง\df_option_combined2.csv')

In [61]:
print(df_1_option['option'].nunique())
df_1_option['option'].unique()

68

array(['ที่นั่งกลางแจ้ง', 'บริการจัดส่ง', 'สั่งกลับบ้าน',
       'นั่งรับประทานที่ร้าน', 'กาแฟรสชาติเยี่ยม', 'ขนมหวานรสชาติเยี่ยม',
       'ตัวเลือกชารสเลิศ', 'ตัวเลือกเบียร์รสชาติเยี่ยม', 'อาหารค่ำ',
       'รับประทานอาหารคนเดียว', 'เหมาะกับการทำงานด้วยแล็ปท็อป', 'กาแฟ',
       'เบียร์', 'ไวน์', 'อาหารจานเล็ก', 'อาหารมื้อดึก', 'แอลกอฮอล์',
       'อาหารเช้า', 'อาหารมื้อสาย', 'อาหารกลางวัน', 'บริการจัดเลี้ยง',
       'ของหวาน', 'ที่นั่ง', 'ห้องน้ำ', 'ความเป็นกันเอง', 'ทันสมัย',
       'โรแมนติก', 'อบอุ่น', 'ขาจร', 'นักศึกษามหาวิทยาลัย',
       'พื้นที่ที่ยอมรับบุคคลข้ามเพศ', 'มาเป็นกลุ่ม',
       'เหมาะสำหรับครอบครัว', 'เหมาะสำหรับ LGBTQ+', 'รับจอง',
       'บัตรเครดิต', 'บัตรเดบิต', 'เมนูสำหรับเด็ก', 'เหมาะสำหรับเด็ก',
       'มีที่จอดจำนวนมาก', 'ที่จอดรถแบบไม่เสียค่าใช้จ่าย',
       'ที่จอดรถริมถนนแบบไม่เสียค่าใช้จ่าย', 'ที่จอดรถแบบเสียค่าใช้จ่าย',
       'อาหารจานด่วน', 'เงียบ', 'เก้าอี้ทานข้าวสำหรับเด็ก',
       'จัดส่งโดยไม่สัมผัส', 'หาที่จอดค่อนข้างยาก',
       'รับสินค้าโดยไม่ต้องลงจากรถ', 'ไดรฟ์ทรู', 'ค็อกเทล',
       'ช่วงลดราคาเครื่องดื่ม', 'ช่วงลดราคาอาหาร', 'ต้อนรับสุนัข',
       'อนุญาตให้นําสุนัขเข้าไปด้านใน', 'อนุญาตให้สุนัขอยู่ด้านนอก',
       'Wi-Fi', 'Wi-Fi ฟรี', 'รับเฉพาะเงินสด',
       'ระบุว่ามีเจ้าของเป็นผู้หญิง', 'ทางเข้าสำหรับเก้าอี้รถเข็น',
       'ที่จอดรถที่เก้าอี้รถเข็นสามารถใช้ได้',
       'ที่นั่งสำหรับเก้าอี้รถเข็น', 'ค็อกเทลรสชาติเยี่ยม',
       'เหล้าดีกรีสูง', 'มีบาร์', 'หรูหรา', 'เหมาะกับกิจกรรมวันเกิดเด็ก'],
      dtype=object)

In [62]:
df_1_option['option'] = df_1_option['option'].replace('Wi-Fi ฟรี', 'Wi-Fi')
print(df_1_option['option'].nunique())
df_1_option['option'].unique()

67

array(['ที่นั่งกลางแจ้ง', 'บริการจัดส่ง', 'สั่งกลับบ้าน',
       'นั่งรับประทานที่ร้าน', 'กาแฟรสชาติเยี่ยม', 'ขนมหวานรสชาติเยี่ยม',
       'ตัวเลือกชารสเลิศ', 'ตัวเลือกเบียร์รสชาติเยี่ยม', 'อาหารค่ำ',
       'รับประทานอาหารคนเดียว', 'เหมาะกับการทำงานด้วยแล็ปท็อป', 'กาแฟ',
       'เบียร์', 'ไวน์', 'อาหารจานเล็ก', 'อาหารมื้อดึก', 'แอลกอฮอล์',
       'อาหารเช้า', 'อาหารมื้อสาย', 'อาหารกลางวัน', 'บริการจัดเลี้ยง',
       'ของหวาน', 'ที่นั่ง', 'ห้องน้ำ', 'ความเป็นกันเอง', 'ทันสมัย',
       'โรแมนติก', 'อบอุ่น', 'ขาจร', 'นักศึกษามหาวิทยาลัย',
       'พื้นที่ที่ยอมรับบุคคลข้ามเพศ', 'มาเป็นกลุ่ม',
       'เหมาะสำหรับครอบครัว', 'เหมาะสำหรับ LGBTQ+', 'รับจอง',
       'บัตรเครดิต', 'บัตรเดบิต', 'เมนูสำหรับเด็ก', 'เหมาะสำหรับเด็ก',
       'มีที่จอดจำนวนมาก', 'ที่จอดรถแบบไม่เสียค่าใช้จ่าย',
       'ที่จอดรถริมถนนแบบไม่เสียค่าใช้จ่าย', 'ที่จอดรถแบบเสียค่าใช้จ่าย',
       'อาหารจานด่วน', 'เงียบ', 'เก้าอี้ทานข้าวสำหรับเด็ก',
       'จัดส่งโดยไม่สัมผัส', 'หาที่จอดค่อนข้างยาก',
       'รับสินค้าโดยไม่ต้องลงจากรถ', 'ไดรฟ์ทรู', 'ค็อกเทล',
       'ช่วงลดราคาเครื่องดื่ม', 'ช่วงลดราคาอาหาร', 'ต้อนรับสุนัข',
       'อนุญาตให้นําสุนัขเข้าไปด้านใน', 'อนุญาตให้สุนัขอยู่ด้านนอก',
       'Wi-Fi', 'รับเฉพาะเงินสด', 'ระบุว่ามีเจ้าของเป็นผู้หญิง',
       'ทางเข้าสำหรับเก้าอี้รถเข็น',
       'ที่จอดรถที่เก้าอี้รถเข็นสามารถใช้ได้',
       'ที่นั่งสำหรับเก้าอี้รถเข็น', 'ค็อกเทลรสชาติเยี่ยม',
       'เหล้าดีกรีสูง', 'มีบาร์', 'หรูหรา', 'เหมาะกับกิจกรรมวันเกิดเด็ก'],
      dtype=object)

In [63]:
print(df_2_option['option'].nunique())
df_2_option['option'].unique()

82

array(['\ue033', 'ทางเข้าสำหรับเก้าอี้รถเข็น',
       'ที่จอดรถที่เก้าอี้รถเข็นสามารถใช้ได้',
       'ที่นั่งสำหรับเก้าอี้รถเข็น', 'จัดส่งโดยไม่สัมผัส', 'บริการจัดส่ง',
       'ไดรฟ์ทรู', 'สั่งกลับบ้าน', 'นั่งรับประทานที่ร้าน',
       'กาแฟรสชาติเยี่ยม', 'ขนมหวานรสชาติเยี่ยม', 'ตัวเลือกชารสเลิศ',
       'รับประทานอาหารคนเดียว', 'เหมาะกับการทำงานด้วยแล็ปท็อป', 'กาแฟ',
       'อาหารจานเล็ก', 'อาหารมื้อสาย', 'อาหารกลางวัน', 'อาหารค่ำ',
       'ของหวาน', 'ห้องน้ำ', 'ความเป็นกันเอง', 'ทันสมัย', 'อบอุ่น',
       'นักศึกษามหาวิทยาลัย', 'มาเป็นกลุ่ม', 'รับจอง', 'เมนูสำหรับเด็ก',
       'เหมาะสำหรับเด็ก', 'ที่จอดรถแบบไม่เสียค่าใช้จ่าย',
       'ที่จอดรถริมถนนแบบไม่เสียค่าใช้จ่าย', 'ที่นั่งกลางแจ้ง',
       'อาหารเช้า', 'ที่นั่ง', 'ขาจร', 'บัตรเครดิต', 'มีที่จอดจำนวนมาก',
       'อาหารจานด่วน', 'โรแมนติก', 'เก้าอี้ทานข้าวสำหรับเด็ก',
       'พื้นที่ที่ยอมรับบุคคลข้ามเพศ', 'เหมาะสำหรับครอบครัว',
       'เหมาะสำหรับ LGBTQ+', 'ห้องน้ำรองรับเก้าอี้รถเข็น',
       'ค็อกเทลรสชาติเยี่ยม', 'ดนตรีสด', 'ตัวเลือกเบียร์รสชาติเยี่ยม',
       'รายการไวน์ชั้นดี', 'ค็อกเทล', 'เบียร์', 'ไวน์', 'เหล้าดีกรีสูง',
       'อาหารมื้อดึก', 'แอลกอฮอล์', 'บริการจัดเลี้ยง', 'มีบาร์', 'เงียบ',
       'หรูหรา', 'เหมาะกับกิจกรรมวันเกิดเด็ก', 'มารับของที่ร้าน',
       'การจัดส่งวันเดียวกัน', 'แวะในช่วงเวลาสั้นๆ',
       'รับสินค้าโดยไม่ต้องลงจากรถ',
       'การชำระเงินผ่าน NFC บนอุปกรณ์เคลื่อนที่', 'โดยปกติต้องรอ',
       'ระบุว่ามีเจ้าของเป็นผู้หญิง', 'ห้องน้ำไม่แบ่งเพศ',
       'หาที่จอดค่อนข้างยาก', 'Wi-Fi', 'Wi-Fi ฟรี', 'ต้องจอง',
       'โรงจอดรถแบบไม่เสียค่าใช้จ่าย', 'ต้อนรับสุนัข',
       'อนุญาตให้นําสุนัขเข้าไปด้านใน', 'รับเฉพาะเงินสด',
       'ตัวเลือกสำหรับมังสวิรัติ', 'ให้บริการอาหารวีแกน',
       'การเลือกซื้อในร้านค้า', 'ช่วงลดราคาเครื่องดื่ม',
       'อนุญาตให้สุนัขอยู่ด้านนอก', 'อาหารออร์แกนิก', 'บัตรเดบิต'],
      dtype=object)

In [64]:
df_2_option['option'] = df_2_option['option'].replace('Wi-Fi ฟรี', 'Wi-Fi')
print(df_2_option['option'].nunique())
df_2_option['option'].unique()

81

array(['\ue033', 'ทางเข้าสำหรับเก้าอี้รถเข็น',
       'ที่จอดรถที่เก้าอี้รถเข็นสามารถใช้ได้',
       'ที่นั่งสำหรับเก้าอี้รถเข็น', 'จัดส่งโดยไม่สัมผัส', 'บริการจัดส่ง',
       'ไดรฟ์ทรู', 'สั่งกลับบ้าน', 'นั่งรับประทานที่ร้าน',
       'กาแฟรสชาติเยี่ยม', 'ขนมหวานรสชาติเยี่ยม', 'ตัวเลือกชารสเลิศ',
       'รับประทานอาหารคนเดียว', 'เหมาะกับการทำงานด้วยแล็ปท็อป', 'กาแฟ',
       'อาหารจานเล็ก', 'อาหารมื้อสาย', 'อาหารกลางวัน', 'อาหารค่ำ',
       'ของหวาน', 'ห้องน้ำ', 'ความเป็นกันเอง', 'ทันสมัย', 'อบอุ่น',
       'นักศึกษามหาวิทยาลัย', 'มาเป็นกลุ่ม', 'รับจอง', 'เมนูสำหรับเด็ก',
       'เหมาะสำหรับเด็ก', 'ที่จอดรถแบบไม่เสียค่าใช้จ่าย',
       'ที่จอดรถริมถนนแบบไม่เสียค่าใช้จ่าย', 'ที่นั่งกลางแจ้ง',
       'อาหารเช้า', 'ที่นั่ง', 'ขาจร', 'บัตรเครดิต', 'มีที่จอดจำนวนมาก',
       'อาหารจานด่วน', 'โรแมนติก', 'เก้าอี้ทานข้าวสำหรับเด็ก',
       'พื้นที่ที่ยอมรับบุคคลข้ามเพศ', 'เหมาะสำหรับครอบครัว',
       'เหมาะสำหรับ LGBTQ+', 'ห้องน้ำรองรับเก้าอี้รถเข็น',
       'ค็อกเทลรสชาติเยี่ยม', 'ดนตรีสด', 'ตัวเลือกเบียร์รสชาติเยี่ยม',
       'รายการไวน์ชั้นดี', 'ค็อกเทล', 'เบียร์', 'ไวน์', 'เหล้าดีกรีสูง',
       'อาหารมื้อดึก', 'แอลกอฮอล์', 'บริการจัดเลี้ยง', 'มีบาร์', 'เงียบ',
       'หรูหรา', 'เหมาะกับกิจกรรมวันเกิดเด็ก', 'มารับของที่ร้าน',
       'การจัดส่งวันเดียวกัน', 'แวะในช่วงเวลาสั้นๆ',
       'รับสินค้าโดยไม่ต้องลงจากรถ',
       'การชำระเงินผ่าน NFC บนอุปกรณ์เคลื่อนที่', 'โดยปกติต้องรอ',
       'ระบุว่ามีเจ้าของเป็นผู้หญิง', 'ห้องน้ำไม่แบ่งเพศ',
       'หาที่จอดค่อนข้างยาก', 'Wi-Fi', 'ต้องจอง',
       'โรงจอดรถแบบไม่เสียค่าใช้จ่าย', 'ต้อนรับสุนัข',
       'อนุญาตให้นําสุนัขเข้าไปด้านใน', 'รับเฉพาะเงินสด',
       'ตัวเลือกสำหรับมังสวิรัติ', 'ให้บริการอาหารวีแกน',
       'การเลือกซื้อในร้านค้า', 'ช่วงลดราคาเครื่องดื่ม',
       'อนุญาตให้สุนัขอยู่ด้านนอก', 'อาหารออร์แกนิก', 'บัตรเดบิต'],
      dtype=object)

In [65]:
df_2_option['option'] = df_2_option['option'].replace('\ue033', np.nan)
print(df_2_option['option'].nunique())
df_2_option['option'].unique()

80

array([nan, 'ทางเข้าสำหรับเก้าอี้รถเข็น',
       'ที่จอดรถที่เก้าอี้รถเข็นสามารถใช้ได้',
       'ที่นั่งสำหรับเก้าอี้รถเข็น', 'จัดส่งโดยไม่สัมผัส', 'บริการจัดส่ง',
       'ไดรฟ์ทรู', 'สั่งกลับบ้าน', 'นั่งรับประทานที่ร้าน',
       'กาแฟรสชาติเยี่ยม', 'ขนมหวานรสชาติเยี่ยม', 'ตัวเลือกชารสเลิศ',
       'รับประทานอาหารคนเดียว', 'เหมาะกับการทำงานด้วยแล็ปท็อป', 'กาแฟ',
       'อาหารจานเล็ก', 'อาหารมื้อสาย', 'อาหารกลางวัน', 'อาหารค่ำ',
       'ของหวาน', 'ห้องน้ำ', 'ความเป็นกันเอง', 'ทันสมัย', 'อบอุ่น',
       'นักศึกษามหาวิทยาลัย', 'มาเป็นกลุ่ม', 'รับจอง', 'เมนูสำหรับเด็ก',
       'เหมาะสำหรับเด็ก', 'ที่จอดรถแบบไม่เสียค่าใช้จ่าย',
       'ที่จอดรถริมถนนแบบไม่เสียค่าใช้จ่าย', 'ที่นั่งกลางแจ้ง',
       'อาหารเช้า', 'ที่นั่ง', 'ขาจร', 'บัตรเครดิต', 'มีที่จอดจำนวนมาก',
       'อาหารจานด่วน', 'โรแมนติก', 'เก้าอี้ทานข้าวสำหรับเด็ก',
       'พื้นที่ที่ยอมรับบุคคลข้ามเพศ', 'เหมาะสำหรับครอบครัว',
       'เหมาะสำหรับ LGBTQ+', 'ห้องน้ำรองรับเก้าอี้รถเข็น',
       'ค็อกเทลรสชาติเยี่ยม', 'ดนตรีสด', 'ตัวเลือกเบียร์รสชาติเยี่ยม',
       'รายการไวน์ชั้นดี', 'ค็อกเทล', 'เบียร์', 'ไวน์', 'เหล้าดีกรีสูง',
       'อาหารมื้อดึก', 'แอลกอฮอล์', 'บริการจัดเลี้ยง', 'มีบาร์', 'เงียบ',
       'หรูหรา', 'เหมาะกับกิจกรรมวันเกิดเด็ก', 'มารับของที่ร้าน',
       'การจัดส่งวันเดียวกัน', 'แวะในช่วงเวลาสั้นๆ',
       'รับสินค้าโดยไม่ต้องลงจากรถ',
       'การชำระเงินผ่าน NFC บนอุปกรณ์เคลื่อนที่', 'โดยปกติต้องรอ',
       'ระบุว่ามีเจ้าของเป็นผู้หญิง', 'ห้องน้ำไม่แบ่งเพศ',
       'หาที่จอดค่อนข้างยาก', 'Wi-Fi', 'ต้องจอง',
       'โรงจอดรถแบบไม่เสียค่าใช้จ่าย', 'ต้อนรับสุนัข',
       'อนุญาตให้นําสุนัขเข้าไปด้านใน', 'รับเฉพาะเงินสด',
       'ตัวเลือกสำหรับมังสวิรัติ', 'ให้บริการอาหารวีแกน',
       'การเลือกซื้อในร้านค้า', 'ช่วงลดราคาเครื่องดื่ม',
       'อนุญาตให้สุนัขอยู่ด้านนอก', 'อาหารออร์แกนิก', 'บัตรเดบิต'],
      dtype=object)

In [66]:
print(df_3_option['option'].nunique())
df_3_option['option'].unique()

77

array(['ทางเข้าสำหรับเก้าอี้รถเข็น',
       'ที่จอดรถที่เก้าอี้รถเข็นสามารถใช้ได้',
       'ที่นั่งสำหรับเก้าอี้รถเข็น', 'ที่นั่งกลางแจ้ง', 'สั่งกลับบ้าน',
       'นั่งรับประทานที่ร้าน', 'กาแฟรสชาติเยี่ยม', 'ขนมหวานรสชาติเยี่ยม',
       'ตัวเลือกชารสเลิศ', 'อาหารเช้า', 'อาหารกลางวัน',
       'รับประทานอาหารคนเดียว', 'เหมาะกับการทำงานด้วยแล็ปท็อป', 'กาแฟ',
       'อาหารจานด่วน', 'อาหารจานเล็ก', 'ของหวาน', 'ที่นั่ง', 'ห้องน้ำ',
       'ความเป็นกันเอง', 'เงียบ', 'ทันสมัย', 'โรแมนติก', 'อบอุ่น', 'ขาจร',
       'นักศึกษามหาวิทยาลัย', 'มาเป็นกลุ่ม', 'รับจอง',
       'เก้าอี้ทานข้าวสำหรับเด็ก', 'เมนูสำหรับเด็ก', 'เหมาะสำหรับเด็ก',
       'มีที่จอดจำนวนมาก', 'ที่จอดรถแบบไม่เสียค่าใช้จ่าย',
       'ที่จอดรถริมถนนแบบไม่เสียค่าใช้จ่าย', 'Wi-Fi', 'Wi-Fi ฟรี',
       'จัดส่งโดยไม่สัมผัส', 'บริการจัดส่ง', 'ช่วงลดราคาเครื่องดื่ม',
       'ช่วงลดราคาอาหาร', 'ตัวเลือกสำหรับมังสวิรัติ', 'อาหารออร์แกนิก',
       'อาหารมื้อสาย', 'อาหารค่ำ', 'บริการจัดเลี้ยง',
       'พื้นที่ที่ยอมรับบุคคลข้ามเพศ', 'เหมาะสำหรับครอบครัว',
       'เหมาะสำหรับ LGBTQ+', 'การชำระเงินผ่าน NFC บนอุปกรณ์เคลื่อนที่',
       'บัตรเครดิต', 'บัตรเดบิต', 'ที่จอดรถในพื้นที่', 'ต้อนรับสุนัข',
       'อนุญาตให้นําสุนัขเข้าไปด้านใน', 'อนุญาตให้สุนัขอยู่ด้านนอก',
       'การเปิดให้บริการที่หน้าร้าน', 'ให้บริการอาหารวีแกน',
       'หาที่จอดค่อนข้างยาก', 'ห้องน้ำรองรับเก้าอี้รถเข็น', 'แอลกอฮอล์',
       'มีบาร์', 'ดนตรีสด', 'ตัวเลือกเบียร์รสชาติเยี่ยม', 'เบียร์',
       'อาหารมื้อดึก', 'หรูหรา', 'เหมาะกับกิจกรรมวันเกิดเด็ก', '\ue033',
       'รับสินค้าโดยไม่ต้องลงจากรถ',
       'ระบบอำนวยความสะดวกช่วยเพิ่มการได้ยิน',
       'ระบุว่ามีเจ้าของเป็นผู้หญิง', 'ไดรฟ์ทรู', 'การแสดงสด', 'ค็อกเทล',
       'ไวน์', 'เหล้าดีกรีสูง', 'ห้องน้ำไม่แบ่งเพศ'], dtype=object)

In [67]:
df_3_option['option'] = df_3_option['option'].replace('Wi-Fi ฟรี', 'Wi-Fi')
print(df_3_option['option'].nunique())
df_3_option['option'].unique()

76

array(['ทางเข้าสำหรับเก้าอี้รถเข็น',
       'ที่จอดรถที่เก้าอี้รถเข็นสามารถใช้ได้',
       'ที่นั่งสำหรับเก้าอี้รถเข็น', 'ที่นั่งกลางแจ้ง', 'สั่งกลับบ้าน',
       'นั่งรับประทานที่ร้าน', 'กาแฟรสชาติเยี่ยม', 'ขนมหวานรสชาติเยี่ยม',
       'ตัวเลือกชารสเลิศ', 'อาหารเช้า', 'อาหารกลางวัน',
       'รับประทานอาหารคนเดียว', 'เหมาะกับการทำงานด้วยแล็ปท็อป', 'กาแฟ',
       'อาหารจานด่วน', 'อาหารจานเล็ก', 'ของหวาน', 'ที่นั่ง', 'ห้องน้ำ',
       'ความเป็นกันเอง', 'เงียบ', 'ทันสมัย', 'โรแมนติก', 'อบอุ่น', 'ขาจร',
       'นักศึกษามหาวิทยาลัย', 'มาเป็นกลุ่ม', 'รับจอง',
       'เก้าอี้ทานข้าวสำหรับเด็ก', 'เมนูสำหรับเด็ก', 'เหมาะสำหรับเด็ก',
       'มีที่จอดจำนวนมาก', 'ที่จอดรถแบบไม่เสียค่าใช้จ่าย',
       'ที่จอดรถริมถนนแบบไม่เสียค่าใช้จ่าย', 'Wi-Fi',
       'จัดส่งโดยไม่สัมผัส', 'บริการจัดส่ง', 'ช่วงลดราคาเครื่องดื่ม',
       'ช่วงลดราคาอาหาร', 'ตัวเลือกสำหรับมังสวิรัติ', 'อาหารออร์แกนิก',
       'อาหารมื้อสาย', 'อาหารค่ำ', 'บริการจัดเลี้ยง',
       'พื้นที่ที่ยอมรับบุคคลข้ามเพศ', 'เหมาะสำหรับครอบครัว',
       'เหมาะสำหรับ LGBTQ+', 'การชำระเงินผ่าน NFC บนอุปกรณ์เคลื่อนที่',
       'บัตรเครดิต', 'บัตรเดบิต', 'ที่จอดรถในพื้นที่', 'ต้อนรับสุนัข',
       'อนุญาตให้นําสุนัขเข้าไปด้านใน', 'อนุญาตให้สุนัขอยู่ด้านนอก',
       'การเปิดให้บริการที่หน้าร้าน', 'ให้บริการอาหารวีแกน',
       'หาที่จอดค่อนข้างยาก', 'ห้องน้ำรองรับเก้าอี้รถเข็น', 'แอลกอฮอล์',
       'มีบาร์', 'ดนตรีสด', 'ตัวเลือกเบียร์รสชาติเยี่ยม', 'เบียร์',
       'อาหารมื้อดึก', 'หรูหรา', 'เหมาะกับกิจกรรมวันเกิดเด็ก', '\ue033',
       'รับสินค้าโดยไม่ต้องลงจากรถ',
       'ระบบอำนวยความสะดวกช่วยเพิ่มการได้ยิน',
       'ระบุว่ามีเจ้าของเป็นผู้หญิง', 'ไดรฟ์ทรู', 'การแสดงสด', 'ค็อกเทล',
       'ไวน์', 'เหล้าดีกรีสูง', 'ห้องน้ำไม่แบ่งเพศ'], dtype=object)

In [68]:
df_3_option['option'] = df_3_option['option'].replace('\ue033', np.nan)
print(df_3_option['option'].nunique())
df_3_option['option'].unique()

75

array(['ทางเข้าสำหรับเก้าอี้รถเข็น',
       'ที่จอดรถที่เก้าอี้รถเข็นสามารถใช้ได้',
       'ที่นั่งสำหรับเก้าอี้รถเข็น', 'ที่นั่งกลางแจ้ง', 'สั่งกลับบ้าน',
       'นั่งรับประทานที่ร้าน', 'กาแฟรสชาติเยี่ยม', 'ขนมหวานรสชาติเยี่ยม',
       'ตัวเลือกชารสเลิศ', 'อาหารเช้า', 'อาหารกลางวัน',
       'รับประทานอาหารคนเดียว', 'เหมาะกับการทำงานด้วยแล็ปท็อป', 'กาแฟ',
       'อาหารจานด่วน', 'อาหารจานเล็ก', 'ของหวาน', 'ที่นั่ง', 'ห้องน้ำ',
       'ความเป็นกันเอง', 'เงียบ', 'ทันสมัย', 'โรแมนติก', 'อบอุ่น', 'ขาจร',
       'นักศึกษามหาวิทยาลัย', 'มาเป็นกลุ่ม', 'รับจอง',
       'เก้าอี้ทานข้าวสำหรับเด็ก', 'เมนูสำหรับเด็ก', 'เหมาะสำหรับเด็ก',
       'มีที่จอดจำนวนมาก', 'ที่จอดรถแบบไม่เสียค่าใช้จ่าย',
       'ที่จอดรถริมถนนแบบไม่เสียค่าใช้จ่าย', 'Wi-Fi',
       'จัดส่งโดยไม่สัมผัส', 'บริการจัดส่ง', 'ช่วงลดราคาเครื่องดื่ม',
       'ช่วงลดราคาอาหาร', 'ตัวเลือกสำหรับมังสวิรัติ', 'อาหารออร์แกนิก',
       'อาหารมื้อสาย', 'อาหารค่ำ', 'บริการจัดเลี้ยง',
       'พื้นที่ที่ยอมรับบุคคลข้ามเพศ', 'เหมาะสำหรับครอบครัว',
       'เหมาะสำหรับ LGBTQ+', 'การชำระเงินผ่าน NFC บนอุปกรณ์เคลื่อนที่',
       'บัตรเครดิต', 'บัตรเดบิต', 'ที่จอดรถในพื้นที่', 'ต้อนรับสุนัข',
       'อนุญาตให้นําสุนัขเข้าไปด้านใน', 'อนุญาตให้สุนัขอยู่ด้านนอก',
       'การเปิดให้บริการที่หน้าร้าน', 'ให้บริการอาหารวีแกน',
       'หาที่จอดค่อนข้างยาก', 'ห้องน้ำรองรับเก้าอี้รถเข็น', 'แอลกอฮอล์',
       'มีบาร์', 'ดนตรีสด', 'ตัวเลือกเบียร์รสชาติเยี่ยม', 'เบียร์',
       'อาหารมื้อดึก', 'หรูหรา', 'เหมาะกับกิจกรรมวันเกิดเด็ก', nan,
       'รับสินค้าโดยไม่ต้องลงจากรถ',
       'ระบบอำนวยความสะดวกช่วยเพิ่มการได้ยิน',
       'ระบุว่ามีเจ้าของเป็นผู้หญิง', 'ไดรฟ์ทรู', 'การแสดงสด', 'ค็อกเทล',
       'ไวน์', 'เหล้าดีกรีสูง', 'ห้องน้ำไม่แบ่งเพศ'], dtype=object)

In [69]:
df_1_option.to_csv('df_1_option_clean.csv', index=False,encoding='utf-8-sig')
df_2_option.to_csv('df_2_option_clean.csv', index=False,encoding='utf-8-sig')
df_3_option.to_csv('df_3_option_clean.csv', index=False,encoding='utf-8-sig')

# df_review

In [70]:
df_1_review = pd.read_csv('โซน หลักหก\df_review_combined.csv')
df_2_review = pd.read_csv('โซน รังสิต\df_review_combined3.csv')
df_3_review = pd.read_csv('โซน คลองหนึ่ง\df_review_combined2.csv')

In [2]:
import pandas as pd

In [3]:
pd.read_csv('https://raw.githubusercontent.com/Eieiz007/Datasets/refs/heads/main/df_main_clean.csv?token=GHSAT0AAAAAADA4QXIATC5E6CGFDA5KCRS42APGLNA')

,name,lat,long,url,rating,comment,sal1,sal2,id_open_close_main,id_customer_main,id_option_main,id_review_main,zone,distance_rangsit,distance_khlong_rangsit,distance_lak_hok
0,Theme Cafe & Bistro,13.961911,100.605467,https://www.google.com/maps/place/Theme+Cafe+%...,4.4,69.0,NaN,NaN,oc_1,ci_1,option_1,review_1,rakhok,3.366392,2.276054,1.470299
1,Shelter specialty coffee,13.962536,100.585268,https://www.google.com/maps/place/Shelter+spec...,4.8,147.0,฿100-200 ต่อคน,78.0,oc_2,ci_2,option_2,review_2,rakhok,3.272303,2.506605,0.863776
2,ภูมิใจเสนอ Poomjai Saner café & coworking space,13.965177,100.599799,https://www.google.com/maps/place/%E0%B8%A0%E0...,4.7,98.0,฿100-200 ต่อคน,30.0,oc_3,ci_3,option_3,review_3,rakhok,2.854773,1.785755,0.793977
3,ใบแมว คาเฟ่แมว รังสิต,13.963064,100.587933,https://www.google.com/maps/place/%E0%B9%83%E0...,4.4,48.0,฿100-200 ต่อคน,21.0,oc_4,ci_4,option_4,review_4,rakhok,3.134911,2.305347,0.583634
4,Mori Cat Cafe’,13.965271,100.589427,https://www.google.com/maps/place/Mori+Cat+Caf...,4.9,124.0,฿100-200 ต่อคน,40.0,oc_5,ci_5,option_5,review_5,rakhok,2.859427,2.012612,0.336883
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
165,Owlvee Soft | Future Park Rangsit,13.989605,100.616846,https://www.google.com/maps/place/Owlvee+Soft+...,4.0,12.0,฿1-100 ต่อคน,4.0,oc_166,ci_166,option_166,review_166,rungsit,2.362460,2.206453,3.722446
166,พิซซ่าเตาดินสองไร่สโลว์ไลฟ์ฟาร์ม รังสิต คลองสาม,14.021239,100.675426,https://www.google.com/maps/place/%E0%B8%9E%E0...,4.5,87.0,฿200-300 ต่อคน,13.0,oc_167,ci_167,option_167,review_167,rungsit,9.332748,9.435511,10.860451
167,ดอยมูเซอคอฟฟี่@ตลาดรังสิต,13.986671,100.613261,https://www.google.com/maps/place/%E0%B8%94%E0...,5.0,1.0,NaN,NaN,oc_168,ci_168,option_168,review_168,rungsit,2.017449,1.722628,3.218512
168,NJ coffee มอรังสิต,13.964200,100.592048,https://www.google.com/maps/place/NJ+coffee+%E...,3.0,2.0,NaN,NaN,oc_169,ci_169,option_169,review_169,rungsit,2.932347,2.005592,0.195462
169,Coffee World - Future Rangsit Triangle 1st Fl,13.987520,100.618070,https://www.google.com/maps/place/Coffee+World...,4.4,19.0,฿100-200 ต่อคน,9.0,oc_170,ci_170,option_170,review_170,rungsit,2.513549,2.243294,3.660618