In [12]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer

In [13]:
import pandas as pd
df_main = pd.read_csv('df_mainlast.csv')
df_main

,name,lat,long,url,rating,comment,sal1,sal2,id_open_close_main,id_customer_main,...,distance_rangsit,distance_khlong_rangsit,distance_lak_hok,distance_rmutt,distance_nbu,distance_bu,distance_tu,distance_rsu,weighted_rating,amazon
0,Cafe’ Amazon RM2076,13.992462,100.648220,https://www.google.com/maps/place/Cafe%E2%80%9...,4.2,115,฿1-100 ต่อคน,7.0,oc_500,ci_500,...,5.750316,5.526942,6.700225,4.288353,2.545516,6.479161,9.992976,7.601018,NaN,1
1,ร้านกาแฟ อเมซอน,13.989384,100.634434,https://www.google.com/maps/place/%E0%B8%A3%E0...,4.4,103,฿1-100 ต่อคน,7.0,oc_501,ci_501,...,4.259964,4.000615,5.225716,2.859694,4.071846,6.043252,9.726211,6.097600,NaN,1
2,Café Amazon สาขา โครงการรังสิตสเตชั่น (สำนักงา...,14.007563,100.614831,https://www.google.com/maps/place/Caf%C3%A9+Am...,3.5,13,฿100-200 ต่อคน,5.0,oc_502,ci_502,...,2.868412,3.431994,5.222182,3.800549,6.185930,3.559212,7.263149,5.678762,NaN,1
3,CAFÉ AMAZON รังสิต 200 ปี ซอย 4,13.989060,100.606208,https://www.google.com/maps/place/CAF%C3%89+AM...,4.3,12,฿1-100 ต่อคน,5.0,oc_503,ci_503,...,1.222328,1.220953,2.970249,1.918096,7.078128,5.654628,9.252708,3.516978,NaN,1
4,Café Amazon สาขาม.รังสิต,13.970512,100.630860,https://www.google.com/maps/place/Caf%C3%A9+Am...,3.5,6,NaN,NaN,oc_504,ci_504,...,4.460949,3.704490,4.173142,1.882750,5.291262,7.916160,11.637719,5.196244,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
221,เฌย Coffee Bar & Exotic Pet,13.983829,100.614168,https://www.google.com/maps/place/%E0%B9%80%E0...,4.7,13,฿1-100 ต่อคน,5.0,oc_248,ci_248,...,2.197607,1.733770,3.073796,1.160561,6.342157,6.193350,9.877228,3.863182,4.569219,0
222,Malong Cafe & ChillBar,13.965698,100.596751,https://www.google.com/maps/place/Malong+Cafe+...,4.7,26,฿200-300 ต่อคน,6.0,oc_250,ci_250,...,2.755512,1.729242,0.461525,2.016550,8.781057,8.388002,11.888851,1.508041,4.599579,0
223,Buddy Cup Coffee,13.987673,100.608295,https://www.google.com/maps/place/Buddy+Cup+Co...,4.3,9,NaN,NaN,oc_256,ci_256,...,1.470166,1.295121,2.961421,1.689413,6.877951,5.784437,9.411094,3.580914,4.463498,0
224,COFFEE CHAN,13.965428,100.596121,https://www.google.com/maps/place/COFFEE+CHAN/...,4.7,26,฿1-100 ต่อคน,8.0,oc_258,ci_258,...,2.781655,1.767087,0.396549,2.090885,8.855410,8.431685,11.924499,1.443738,4.599579,0
225,Tea & Coffee Home,13.987088,100.613803,https://www.google.com/maps/place/Tea+%26+Coff...,4.7,20,NaN,NaN,oc_261,ci_261,...,2.065918,1.793928,3.292555,1.521752,6.303633,5.830216,9.512763,4.018215,4.587529,0

In [14]:
df_main.columns

Index(['name', 'lat', 'long', 'url', 'rating', 'comment', 'sal1', 'sal2',
       'id_open_close_main', 'id_customer_main', 'id_option_main',
       'id_review_main', 'zone', 'distance_rangsit', 'distance_khlong_rangsit',
       'distance_lak_hok', 'distance_rmutt', 'distance_nbu', 'distance_bu',
       'distance_tu', 'distance_rsu', 'weighted_rating', 'amazon'],
      dtype='object')

In [15]:
df_option = pd.read_csv('df_option.csv')
df_option

     id_option_main                              option
0          option_1                     ที่นั่งกลางแจ้ง
1          option_1                        บริการจัดส่ง
2          option_1                        สั่งกลับบ้าน
3          option_1                นั่งรับประทานที่ร้าน
4          option_1                    กาแฟรสชาติเยี่ยม
...             ...                                 ...
5777     option_265                             ทันสมัย
5778     option_265                         มาเป็นกลุ่ม
5779     option_265                      เมนูสำหรับเด็ก
5780     option_265                     เหมาะสำหรับเด็ก
5781     option_265  ที่จอดรถริมถนนแบบไม่เสียค่าใช้จ่าย

[5782 rows x 2 columns]

In [16]:
df_review = pd.read_csv('df_review.csv')
df_review

,id_review_main,review_rating,review_text,sentiment
0,review_1,3,เด็กเสิร์ฟน้อยขนาดไปวันเสาร์นั่งกินอาหารตั้งแต...,neg
1,review_1,5,มาครั้งแรกอาหารอร่อยถูกปาก.บรรยากาศดี.กาแฟอร่อ...,pos
2,review_1,4,บรรยากาศดีค่ะ ถ้ามาช่วงค่ำมีดนตรี อาหาร น่าจ...,pos
3,review_1,5,ร้านสวยยยยมากกก บรรยากาศดี ตอนแรกไม่ได้ตั้งใจแ...,pos
4,review_1,4,Theme Cafe & Bistro คาเฟ่โรงนาสีแดงสไตล์ยุโรปต...,pos
...,...,...,...,...
5420,review_265,4,พูดจาถือว่าผ่าน บริการถือว่าโอเค แต่ติดตรงที่ก...,neu
5421,review_265,5,อาหารอร่อย ร้านสะอาด พนักงานน่ารัก กาแฟเป็น al...,pos
5422,review_265,5,มีที่นั่งให้นั่ง ชอบค่ะ เหมาะกับการนั่งทำงาน,pos
5423,review_265,5,positive,pos
5424,review_265,5,positive,pos

In [17]:
a=df_review[df_review['id_review_main'] == 'review_1']
len(a)

69

In [18]:
# Merge df_main กับ df_option
merged_df = pd.merge(df_main, df_option, on='id_option_main', how='left')

# Merge เอาเฉพาะคอลัมน์ sentiment จาก df_review
merged_df = pd.merge(
    merged_df,
    df_review[['id_review_main', 'sentiment']],  # เอาแค่ 2 คอลัมน์นี้
    on='id_review_main',
    how='left'
)

# merged_df[merged_df['sentiment'] == 'neu']

# สร้างตารางนับ sentiment ต่อร้าน
sentiment_counts = merged_df.groupby('name')['sentiment'].value_counts().unstack(fill_value=0).reset_index()

# รวมกลับเข้า merged_df ด้วย left join
merged_df = pd.merge(merged_df, sentiment_counts, on='name', how='left')

merged_df

,name,lat,long,url,rating,comment,sal1,sal2,id_open_close_main,id_customer_main,...,distance_bu,distance_tu,distance_rsu,weighted_rating,amazon,option,sentiment,neg,neu,pos
0,Cafe’ Amazon RM2076,13.992462,100.648220,https://www.google.com/maps/place/Cafe%E2%80%9...,4.2,115,฿1-100 ต่อคน,7.0,oc_500,ci_500,...,6.479161,9.992976,7.601018,NaN,1,NaN,NaN,NaN,NaN,NaN
1,ร้านกาแฟ อเมซอน,13.989384,100.634434,https://www.google.com/maps/place/%E0%B8%A3%E0...,4.4,103,฿1-100 ต่อคน,7.0,oc_501,ci_501,...,6.043252,9.726211,6.097600,NaN,1,NaN,NaN,NaN,NaN,NaN
2,Café Amazon สาขา โครงการรังสิตสเตชั่น (สำนักงา...,14.007563,100.614831,https://www.google.com/maps/place/Caf%C3%A9+Am...,3.5,13,฿100-200 ต่อคน,5.0,oc_502,ci_502,...,3.559212,7.263149,5.678762,NaN,1,NaN,NaN,NaN,NaN,NaN
3,CAFÉ AMAZON รังสิต 200 ปี ซอย 4,13.989060,100.606208,https://www.google.com/maps/place/CAF%C3%89+AM...,4.3,12,฿1-100 ต่อคน,5.0,oc_503,ci_503,...,5.654628,9.252708,3.516978,NaN,1,NaN,NaN,NaN,NaN,NaN
4,Café Amazon สาขาม.รังสิต,13.970512,100.630860,https://www.google.com/maps/place/Caf%C3%A9+Am...,3.5,6,NaN,NaN,oc_504,ci_504,...,7.916160,11.637719,5.196244,NaN,1,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88246,Tea & Coffee Home,13.987088,100.613803,https://www.google.com/maps/place/Tea+%26+Coff...,4.7,20,NaN,NaN,oc_261,ci_261,...,5.830216,9.512763,4.018215,4.587529,0,ของหวาน,NaN,NaN,NaN,NaN
88247,Tea & Coffee Home,13.987088,100.613803,https://www.google.com/maps/place/Tea+%26+Coff...,4.7,20,NaN,NaN,oc_261,ci_261,...,5.830216,9.512763,4.018215,4.587529,0,ความเป็นกันเอง,NaN,NaN,NaN,NaN
88248,Tea & Coffee Home,13.987088,100.613803,https://www.google.com/maps/place/Tea+%26+Coff...,4.7,20,NaN,NaN,oc_261,ci_261,...,5.830216,9.512763,4.018215,4.587529,0,ทันสมัย,NaN,NaN,NaN,NaN
88249,Tea & Coffee Home,13.987088,100.613803,https://www.google.com/maps/place/Tea+%26+Coff...,4.7,20,NaN,NaN,oc_261,ci_261,...,5.830216,9.512763,4.018215,4.587529,0,เมนูสำหรับเด็ก,NaN,NaN,NaN,NaN
88250,Tea & Coffee Home,13.987088,100.613803,https://www.google.com/maps/place/Tea+%26+Coff...,4.7,20,NaN,NaN,oc_261,ci_261,...,5.830216,9.512763,4.018215,4.587529,0,เหมาะสำหรับเด็ก,NaN,NaN,NaN,NaN

In [ ]:
# รวม options ต่อร้าน โดยใช้ id_customer_main เป็น key
aggregated_options = merged_df.groupby('id_customer_main')['option'] \
    .apply(lambda x: ' '.join(x.dropna().astype(str))) \
    .reset_index()

# เปลี่ยนชื่อคอลัมน์เป็น all_options
aggregated_options.rename(columns={'option': 'all_options'}, inplace=True)

In [ ]:
# ดึงเฉพาะข้อมูลร้านไม่ซ้ำจาก df_main
df_main_unique = df_main.drop_duplicates(subset=['id_customer_main'])

In [ ]:
final_df_for_tfidf

NameError: name 'final_df_for_tfidf' is not defined

In [ ]:
final_df_for_tfidf[all_options].unique()

NameError: name 'final_df_for_tfidf' is not defined

In [ ]:
print(final_df_for_tfidf['all_options'])

0      ที่นั่งกลางแจ้ง ที่นั่งกลางแจ้ง ที่นั่งกลางแจ้...
1      ที่นั่งกลางแจ้ง ที่นั่งกลางแจ้ง ที่นั่งกลางแจ้...
2      ที่นั่งกลางแจ้ง ที่นั่งกลางแจ้ง ที่นั่งกลางแจ้...
3      จัดส่งโดยไม่สัมผัส จัดส่งโดยไม่สัมผัส จัดส่งโด...
4      รับสินค้าโดยไม่ต้องลงจากรถ รับสินค้าโดยไม่ต้อง...
                             ...
176    สั่งกลับบ้าน สั่งกลับบ้าน สั่งกลับบ้าน สั่งกลั...
177    บริการจัดส่ง บริการจัดส่ง บริการจัดส่ง บริการจ...
178    ที่นั่งกลางแจ้ง ที่นั่งกลางแจ้ง ที่นั่งกลางแจ้...
179    บริการจัดส่ง บริการจัดส่ง บริการจัดส่ง บริการจ...
180    บริการจัดส่ง สั่งกลับบ้าน นั่งรับประทานที่ร้าน...
Name: all_options, Length: 181, dtype: object

In [ ]:

# ทำ TF-IDF

from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd

# ✅ กลุ่มคำทั้งหมดที่คุณให้มา (cleaned เป็น list)
custom_phrases = [
    'ที่นั่งกลางแจ้ง', 'บริการจัดส่ง', 'สั่งกลับบ้าน', 'นั่งรับประทานที่ร้าน',
    'กาแฟรสชาติเยี่ยม', 'ขนมหวานรสชาติเยี่ยม', 'ตัวเลือกชารสเลิศ',
    'ตัวเลือกเบียร์รสชาติเยี่ยม', 'อาหารค่ำ', 'รับประทานอาหารคนเดียว',
    'เหมาะกับการทำงานด้วยแล็ปท็อป', 'กาแฟ', 'เบียร์', 'ไวน์', 'อาหารจานเล็ก',
    'อาหารมื้อดึก', 'แอลกอฮอล์', 'อาหารเช้า', 'อาหารมื้อสาย', 'อาหารกลางวัน',
    'บริการจัดเลี้ยง', 'ของหวาน', 'ที่นั่ง', 'ห้องน้ำ', 'ความเป็นกันเอง',
    'ทันสมัย', 'โรแมนติก', 'อบอุ่น', 'ขาจร', 'นักศึกษามหาวิทยาลัย',
    'พื้นที่ที่ยอมรับบุคคลข้ามเพศ', 'มาเป็นกลุ่ม', 'เหมาะสำหรับครอบครัว',
    'เหมาะสำหรับ LGBTQ+', 'รับจอง', 'บัตรเครดิต', 'บัตรเดบิต', 'เมนูสำหรับเด็ก',
    'เหมาะสำหรับเด็ก', 'มีที่จอดจำนวนมาก', 'ที่จอดรถแบบไม่เสียค่าใช้จ่าย',
    'ที่จอดรถริมถนนแบบไม่เสียค่าใช้จ่าย', 'ที่จอดรถแบบเสียค่าใช้จ่าย',
    'อาหารจานด่วน', 'เงียบ', 'เก้าอี้ทานข้าวสำหรับเด็ก', 'จัดส่งโดยไม่สัมผัส',
    'หาที่จอดค่อนข้างยาก', 'รับสินค้าโดยไม่ต้องลงจากรถ', 'ไดรฟ์ทรู', 'ค็อกเทล',
    'ช่วงลดราคาเครื่องดื่ม', 'ช่วงลดราคาอาหาร', 'ต้อนรับสุนัข',
    'อนุญาตให้นําสุนัขเข้าไปด้านใน', 'อนุญาตให้สุนัขอยู่ด้านนอก', 'Wi-Fi',
    'รับเฉพาะเงินสด', 'ระบุว่ามีเจ้าของเป็นผู้หญิง', 'ทางเข้าสำหรับเก้าอี้รถเข็น',
    'ที่จอดรถที่เก้าอี้รถเข็นสามารถใช้ได้', 'ที่นั่งสำหรับเก้าอี้รถเข็น',
    'ค็อกเทลรสชาติเยี่ยม', 'เหล้าดีกรีสูง', 'มีบาร์', 'หรูหรา',
    'เหมาะกับกิจกรรมวันเกิดเด็ก', 'ตัวเลือกสำหรับมังสวิรัติ', 'อาหารออร์แกนิก',
    'การชำระเงินผ่าน NFC บนอุปกรณ์เคลื่อนที่', 'ที่จอดรถในพื้นที่',
    'การเปิดให้บริการที่หน้าร้าน', 'ให้บริการอาหารวีแกน',
    'ห้องน้ำรองรับเก้าอี้รถเข็น', 'ดนตรีสด', 'ระบบอำนวยความสะดวกช่วยเพิ่มการได้ยิน',
    'การแสดงสด', 'ห้องน้ำไม่แบ่งเพศ', 'รายการไวน์ชั้นดี', 'มารับของที่ร้าน',
    'การจัดส่งวันเดียวกัน', 'แวะในช่วงเวลาสั้นๆ', 'โดยปกติต้องรอ', 'ต้องจอง',
    'โรงจอดรถแบบไม่เสียค่าใช้จ่าย', 'การเลือกซื้อในร้านค้า', 'อาหารสำเร็จ',
    'ต้องนัดหมายล่วงหน้า', 'ส่วนลดสำหรับครอบครัว', 'ส่วนลดสําหรับเด็ก',
    'แนะนำให้จองอาหารมื้อสาย', 'แนะนำให้จองอาหารกลางวัน', 'แนะนำให้จองอาหารค่ำ',
    'อาหาร', 'หาที่จอดยาก', 'อาหารฮาลาล', 'กีฬา', 'อุปกรณ์อิเล็กทรอนิกส์', 'บุฟเฟ่ต์'
]

# ✅ เตรียมข้อมูล (เช่นจาก final_df_for_tfidf['all_options'])
corpus = final_df_for_tfidf['all_options'].fillna('')

# ✅ ใช้ TF-IDF โดยใส่ vocabulary เอง
vectorizer = TfidfVectorizer(vocabulary=custom_phrases, token_pattern=r"[^ ]+")
tfidf_matrix = vectorizer.fit_transform(corpus)

# ✅ แปลงเป็น DataFrame
tfidf_df = pd.DataFrame(tfidf_matrix.toarray(), columns=vectorizer.get_feature_names_out())

# ✅ ดูคำที่ TF-IDF รวมสูงสุด
top_phrases = tfidf_df.sum().sort_values(ascending=False).head(20)
print(top_phrases)

ตัวเลือกชารสเลิศ                      27.718880
ความเป็นกันเอง                        27.577056
นั่งรับประทานที่ร้าน                  27.517250
กาแฟรสชาติเยี่ยม                      27.409224
สั่งกลับบ้าน                          27.321459
กาแฟ                                  27.278450
ขนมหวานรสชาติเยี่ยม                   25.890819
ของหวาน                               25.795380
ทันสมัย                               25.396187
อบอุ่น                                25.185031
รับประทานอาหารคนเดียว                 24.979631
ที่จอดรถริมถนนแบบไม่เสียค่าใช้จ่าย    24.486647
มาเป็นกลุ่ม                           24.007548
เหมาะสำหรับเด็ก                       23.413935
ขาจร                                  22.620345
ห้องน้ำ                               22.484207
เมนูสำหรับเด็ก                        22.385449
บริการจัดส่ง                          22.331739
นักศึกษามหาวิทยาลัย                   19.123308
อาหารกลางวัน                          16.232640
dtype: float64

c:\Users\ppich\anaconda3\Lib\site-packages\sklearn\feature_extraction\text.py:1381: UserWarning: Upper case characters found in vocabulary while 'lowercase' is True. These entries will not be matched with any documents
  warnings.warn(